// ─────────────────────────────────────────────
// BUSH LEAGUE — CORE DATA
// ─────────────────────────────────────────────

// ── FRANCHISE REGISTRY ──
export const FRANCHISES = [
  { id: "Kam",       owner: "Kameron Zitelli"                     },
  { id: "Salsa Dick", owner: "Wylie Lopez"                         },
  { id: "Fritz",      owner: "Fritz L'Esperance"                   },
  { id: "Boomer",     owner: "Timothy Jacobus"                     },
  { id: "Devany",     owner: "Conor Devany"                        },
  { id: "Magoo",      owner: "Ryan McGovern"                       },
  { id: "DDC",        owner: "Tom Mysliwiec / Kyle Koehler"        },
  { id: "Trust",      owner: "Joe Cristantiello / Matthew Tietjen" },
  { id: "Biceps Inc", owner: "Joe Grimaldi / Tyler Johnson"        },
  { id: "Sherlock",   owner: "Brian Sherlock"                      },
  { id: "Vidz",       owner: "Sean Vidolin"                        },
  { id: "Tino", owner: "Kyle Sorrentino"                     },
  // Historical / inactive
  { id: "Salizzoni",  owner: "Craig Salizzoni"                     },
  { id: "Hatala",     owner: "Michael Hatala"                      },
  { id: "Fraga",      owner: "John Fraga"                          },
  { id: "Herman",     owner: "Shana Herman"                        },
  { id: "Pedersen",   owner: "Soren Pedersen"                      },
  { id: "WLopez",     owner: "William Lopez"                       },
  { id: "Mysliwiec",  owner: "Tom Mysliwiec"                       },
];

// ── SEASON RESULTS ──
export const SEASONS = [
  {
    year: 2025, champion: "Biceps Inc", runnerUp: "Kam", third: "Boomer",
    playoffs: [
      { franchise: "Biceps Inc", seed: 1, finish: 1 },
      { franchise: "Kam",        seed: 2, finish: 2 },
      { franchise: "Boomer",     seed: 4, finish: 3 },
      { franchise: "Vidz",       seed: 3, finish: 4 },
      { franchise: "Salsa Dick", seed: 5, finish: 5 },
      { franchise: "Magoo",      seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Biceps Inc", rec: "12-2-0", pf: 1793.32, pa: 1380.66 },
      { franchise: "Kam",        rec: "10-4-0", pf: 1735.28, pa: 1474.26 },
      { franchise: "Boomer",     rec: "9-5-0",  pf: 1527.02, pa: 1459.64 },
      { franchise: "Vidz",       rec: "10-4-0", pf: 1776.64, pa: 1550.02 },
      { franchise: "Salsa Dick", rec: "9-5-0",  pf: 1430.48, pa: 1296.98 },
      { franchise: "Magoo",      rec: "7-7-0",  pf: 1516.42, pa: 1628.62 },
      { franchise: "Devany",     rec: "7-7-0",  pf: 1479.28, pa: 1505.82 },
      { franchise: "Fritz",      rec: "4-10-0", pf: 1407.70, pa: 1620.62 },
      { franchise: "DDC",        rec: "6-8-0",  pf: 1425.38, pa: 1552.46 },
      { franchise: "Sherlock",   rec: "5-9-0",  pf: 1361.10, pa: 1542.06 },
      { franchise: "Tino",       rec: "3-11-0", pf: 1271.92, pa: 1537.38 },
      { franchise: "Trust",      rec: "2-12-0", pf: 1370.60, pa: 1546.62 },
    ],
  },
  {
    year: 2024, champion: "Boomer", runnerUp: "Fritz", third: "Biceps Inc",
    playoffs: [
      { franchise: "Boomer",     seed: 1, finish: 1 },
      { franchise: "Fritz",      seed: 3, finish: 2 },
      { franchise: "Biceps Inc", seed: 2, finish: 3 },
      { franchise: "Vidz",       seed: 4, finish: 4 },
      { franchise: "Tino", seed: 5, finish: 5 },
      { franchise: "Magoo",      seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Boomer",     rec: "12-2-0", pf: 1624.78, pa: 1392.80 },
      { franchise: "Fritz",      rec: "10-4-0", pf: 1752.32, pa: 1508.16 },
      { franchise: "Biceps Inc", rec: "10-4-0", pf: 1643.92, pa: 1398.14 },
      { franchise: "Vidz",       rec: "8-6-0",  pf: 1621.12, pa: 1517.16 },
      { franchise: "Magoo",      rec: "8-6-0",  pf: 1480.24, pa: 1523.22 },
      { franchise: "Tino", rec: "8-6-0",  pf: 1595.30, pa: 1552.34 },
      { franchise: "Kam",       rec: "5-9-0",  pf: 1590.66, pa: 1562.00 },
      { franchise: "Devany",     rec: "4-10-0", pf: 1239.98, pa: 1480.92 },
      { franchise: "DDC",        rec: "6-8-0",  pf: 1586.16, pa: 1585.30 },
      { franchise: "Sherlock",   rec: "5-9-0",  pf: 1550.66, pa: 1557.56 },
      { franchise: "Salsa Dick", rec: "6-8-0",  pf: 1276.06, pa: 1476.24 },
      { franchise: "Trust",      rec: "2-12-0", pf: 1370.20, pa: 1777.56 },
    ],
  },
  {
    year: 2023, champion: "Tino", runnerUp: "Trust", third: "Salsa Dick",
    playoffs: [
      { franchise: "Tino", seed: 3, finish: 1 },
      { franchise: "Trust",      seed: 1, finish: 2 },
      { franchise: "Salsa Dick", seed: 2, finish: 3 },
      { franchise: "Boomer",     seed: 6, finish: 4 },
      { franchise: "Kam",       seed: 5, finish: 5 },
      { franchise: "Devany",     seed: 4, finish: 6 },
    ],
    standings: [
      { franchise: "Tino", rec: "9-5-0",  pf: 1542.12, pa: 1551.44 },
      { franchise: "Trust",      rec: "12-2-0", pf: 1819.04, pa: 1462.28 },
      { franchise: "Salsa Dick", rec: "8-6-0",  pf: 1579.78, pa: 1561.16 },
      { franchise: "Boomer",     rec: "7-7-0",  pf: 1481.08, pa: 1581.32 },
      { franchise: "Kam",       rec: "8-6-0",  pf: 1490.70, pa: 1516.12 },
      { franchise: "Devany",     rec: "9-5-0",  pf: 1486.16, pa: 1342.46 },
      { franchise: "Vidz",       rec: "5-9-0",  pf: 1569.80, pa: 1611.02 },
      { franchise: "DDC",        rec: "4-10-0", pf: 1502.62, pa: 1601.68 },
      { franchise: "Biceps Inc", rec: "5-9-0",  pf: 1522.68, pa: 1593.38 },
      { franchise: "Fritz",      rec: "6-8-0",  pf: 1498.46, pa: 1482.74 },
      { franchise: "Sherlock",   rec: "4-10-0", pf: 1354.98, pa: 1530.54 },
      { franchise: "Magoo",      rec: "7-7-0",  pf: 1472.74, pa: 1486.02 },
    ],
  },
  {
    year: 2022, champion: "Kam", runnerUp: "Vidz", third: "Biceps Inc",
    playoffs: [
      { franchise: "Kam",       seed: 1, finish: 1 },
      { franchise: "Vidz",       seed: 3, finish: 2 },
      { franchise: "Biceps Inc", seed: 2, finish: 3 },
      { franchise: "Devany",     seed: 4, finish: 4 },
      { franchise: "Boomer",     seed: 5, finish: 5 },
      { franchise: "Fritz",      seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Kam",       rec: "11-3-0", pf: 1556.36, pa: 1372.50 },
      { franchise: "Vidz",       rec: "10-4-0", pf: 1622.10, pa: 1448.88 },
      { franchise: "Biceps Inc", rec: "8-6-0",  pf: 1267.88, pa: 1362.52 },
      { franchise: "Devany",     rec: "9-5-0",  pf: 1637.48, pa: 1441.04 },
      { franchise: "Boomer",     rec: "7-7-0",  pf: 1530.08, pa: 1558.30 },
      { franchise: "Fritz",      rec: "7-7-0",  pf: 1496.16, pa: 1423.84 },
      { franchise: "DDC",        rec: "6-8-0",  pf: 1522.20, pa: 1599.30 },
      { franchise: "Tino", rec: "4-10-0", pf: 1468.64, pa: 1657.40 },
      { franchise: "Sherlock",   rec: "7-7-0",  pf: 1463.36, pa: 1457.62 },
      { franchise: "Magoo",      rec: "5-9-0",  pf: 1570.56, pa: 1563.90 },
      { franchise: "Trust",      rec: "6-8-0",  pf: 1552.34, pa: 1561.32 },
      { franchise: "Salsa Dick", rec: "4-10-0", pf: 1329.40, pa: 1569.94 },
    ],
  },
  {
    year: 2021, champion: "Magoo", runnerUp: "DDC", third: "Devany",
    playoffs: [
      { franchise: "Magoo",      seed: 2, finish: 1 },
      { franchise: "DDC",        seed: 4, finish: 2 },
      { franchise: "Devany",     seed: 3, finish: 3 },
      { franchise: "Biceps Inc", seed: 1, finish: 4 },
      { franchise: "Trust",      seed: 5, finish: 5 },
      { franchise: "Salsa Dick", seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Magoo",      rec: "11-3-0", pf: 1728.64, pa: 1388.84 },
      { franchise: "DDC",        rec: "8-6-0",  pf: 1407.40, pa: 1390.82 },
      { franchise: "Devany",     rec: "8-6-0",  pf: 1450.78, pa: 1483.34 },
      { franchise: "Biceps Inc", rec: "12-2-0", pf: 1658.12, pa: 1221.00 },
      { franchise: "Salsa Dick", rec: "7-7-0",  pf: 1347.36, pa: 1428.72 },
      { franchise: "Trust",      rec: "7-7-0",  pf: 1456.04, pa: 1373.88 },
      { franchise: "Fritz",      rec: "6-8-0",  pf: 1427.02, pa: 1465.08 },
      { franchise: "Kam",       rec: "6-8-0",  pf: 1302.14, pa: 1475.28 },
      { franchise: "Boomer",     rec: "6-8-0",  pf: 1366.18, pa: 1267.22 },
      { franchise: "Vidz",       rec: "4-10-0", pf: 1204.44, pa: 1585.48 },
      { franchise: "Sherlock",   rec: "4-10-0", pf: 1175.02, pa: 1395.78 },
      { franchise: "Tino", rec: "5-9-0",  pf: 1365.46, pa: 1413.16 },
    ],
  },
  {
    year: 2020, champion: "Salsa Dick", runnerUp: "Magoo", third: "Sherlock",
    note: "COVID year — 13-game regular season",
    playoffs: [
      { franchise: "Salsa Dick", seed: 2, finish: 1 },
      { franchise: "Magoo",      seed: 5, finish: 2 },
      { franchise: "Sherlock",   seed: 6, finish: 3 },
      { franchise: "Boomer",     seed: 1, finish: 4 },
      { franchise: "Devany",     seed: 4, finish: 5 },
      { franchise: "Kam",       seed: 3, finish: 6 },
    ],
    standings: [
      { franchise: "Salsa Dick", rec: "9-4-0",  pf: 1456.72, pa: 1132.26 },
      { franchise: "Magoo",      rec: "7-6-0",  pf: 1342.82, pa: 1427.24 },
      { franchise: "Sherlock",   rec: "7-6-0",  pf: 1335.32, pa: 1254.94 },
      { franchise: "Boomer",     rec: "10-3-0", pf: 1272.42, pa: 1099.52 },
      { franchise: "Devany",     rec: "7-6-0",  pf: 1437.02, pa: 1247.34 },
      { franchise: "Kam",       rec: "8-5-0",  pf: 1489.90, pa: 1471.44 },
      { franchise: "DDC",        rec: "2-11-0", pf: 1136.32, pa: 1482.18 },
      { franchise: "Vidz",       rec: "5-8-0",  pf: 1196.70, pa: 1207.44 },
      { franchise: "Fritz",      rec: "6-7-0",  pf: 1245.48, pa: 1291.76 },
      { franchise: "Trust",      rec: "7-6-0",  pf: 1262.00, pa: 1355.02 },
      { franchise: "Biceps Inc", rec: "6-7-0",  pf: 1277.56, pa: 1379.82 },
      { franchise: "Tino", rec: "4-9-0",  pf: 1303.08, pa: 1406.38 },
    ],
  },
  {
    year: 2019, champion: "Biceps Inc", runnerUp: "Boomer", third: "Salsa Dick",
    playoffs: [
      { franchise: "Biceps Inc", seed: 1, finish: 1 },
      { franchise: "Boomer",     seed: 3, finish: 2 },
      { franchise: "Salsa Dick", seed: 4, finish: 3 },
      { franchise: "Vidz",       seed: 2, finish: 4 },
      { franchise: "Tino", seed: 6, finish: 5 },
      { franchise: "Devany",     seed: 5, finish: 6 },
    ],
    standings: [
      { franchise: "Biceps Inc", rec: "11-2-0", pf: 1428.30, pa: 1251.66 },
      { franchise: "Boomer",     rec: "9-4-0",  pf: 1397.48, pa: 1251.04 },
      { franchise: "Salsa Dick", rec: "8-5-0",  pf: 1405.48, pa: 1379.00 },
      { franchise: "Vidz",       rec: "9-4-0",  pf: 1420.10, pa: 1310.66 },
      { franchise: "Tino", rec: "6-7-0",  pf: 1291.16, pa: 1254.16 },
      { franchise: "Devany",     rec: "6-7-0",  pf: 1390.06, pa: 1320.08 },
      { franchise: "Kam",       rec: "4-9-0",  pf: 1321.84, pa: 1421.66 },
      { franchise: "DDC",        rec: "5-8-0",  pf: 1251.40, pa: 1373.96 },
      { franchise: "Sherlock",   rec: "5-8-0",  pf: 1228.50, pa: 1383.02 },
      { franchise: "Fritz",      rec: "6-7-0",  pf: 1282.38, pa: 1325.08 },
      { franchise: "Trust",      rec: "5-8-0",  pf: 1281.98, pa: 1315.02 },
      { franchise: "Magoo",      rec: "4-9-0",  pf: 1171.70, pa: 1285.04 },
    ],
  },
  {
    year: 2018, champion: "Biceps Inc", runnerUp: "Magoo", third: "Sherlock",
    playoffs: [
      { franchise: "Biceps Inc", seed: 4, finish: 1 },
      { franchise: "Magoo",      seed: 3, finish: 2 },
      { franchise: "Sherlock",   seed: 6, finish: 3 },
      { franchise: "Tino", seed: 1, finish: 4 },
      { franchise: "Devany",     seed: 5, finish: 5 },
      { franchise: "Fritz",      seed: 2, finish: 6 },
    ],
    standings: [
      { franchise: "Biceps Inc", rec: "8-5-0",  pf: 1294.18, pa: 1279.00 },
      { franchise: "Magoo",      rec: "8-5-0",  pf: 1460.80, pa: 1414.68 },
      { franchise: "Sherlock",   rec: "7-6-0",  pf: 1489.94, pa: 1341.74 },
      { franchise: "Tino", rec: "10-3-0", pf: 1455.68, pa: 1291.12 },
      { franchise: "Devany",     rec: "7-6-0",  pf: 1513.98, pa: 1398.54 },
      { franchise: "Fritz",      rec: "8-5-0",  pf: 1392.76, pa: 1304.28 },
      { franchise: "Boomer",     rec: "3-10-0", pf: 1099.22, pa: 1200.34 },
      { franchise: "Kam",       rec: "5-8-0",  pf: 1330.70, pa: 1439.74 },
      { franchise: "Trust",      rec: "6-7-0",  pf: 1347.88, pa: 1383.50 },
      { franchise: "DDC",        rec: "5-8-0",  pf: 1283.70, pa: 1364.54 },
      { franchise: "Salsa Dick", rec: "6-7-0",  pf: 1266.80, pa: 1369.82 },
      { franchise: "Vidz",       rec: "5-8-0",  pf: 1279.70, pa: 1428.04 },
    ],
  },
  {
    year: 2017, champion: "Fritz", runnerUp: "Vidz", third: "Kam",
    playoffs: [
      { franchise: "Fritz",      seed: 1, finish: 1 },
      { franchise: "Vidz",       seed: 2, finish: 2 },
      { franchise: "Kam",       seed: 3, finish: 3 },
      { franchise: "Salsa Dick", seed: 5, finish: 4 },
      { franchise: "Biceps Inc", seed: 4, finish: 5 },
      { franchise: "Boomer",     seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Fritz",      rec: "9-4-0",  pf: 1325.08, pa: 1166.18 },
      { franchise: "Vidz",       rec: "8-5-0",  pf: 1246.34, pa: 1219.68 },
      { franchise: "Kam",       rec: "8-5-0",  pf: 1332.44, pa: 1259.64 },
      { franchise: "Salsa Dick", rec: "7-6-0",  pf: 1149.20, pa: 1240.34 },
      { franchise: "Biceps Inc", rec: "7-6-0",  pf: 1162.16, pa: 1078.84 },
      { franchise: "Boomer",     rec: "7-6-0",  pf: 1102.74, pa: 1092.72 },
      { franchise: "DDC",        rec: "6-7-0",  pf: 1200.40, pa: 1249.68 },
      { franchise: "Devany",     rec: "6-7-0",  pf: 1214.38, pa: 1171.34 },
      { franchise: "Tino", rec: "5-8-0",  pf: 1090.24, pa: 1310.46 },
      { franchise: "Sherlock",   rec: "5-8-0",  pf: 1233.12, pa: 1229.64 },
      { franchise: "Magoo",      rec: "6-7-0",  pf: 1104.60, pa: 1068.18 },
      { franchise: "Trust",      rec: "4-9-0",  pf: 1064.92, pa: 1138.92 },
    ],
  },
  {
    year: 2016, champion: "Trust", runnerUp: "Vidz", third: "Biceps Inc",
    playoffs: [
      { franchise: "Trust",      seed: 6, finish: 1 },
      { franchise: "Vidz",       seed: 1, finish: 2 },
      { franchise: "Biceps Inc", seed: 2, finish: 3 },
      { franchise: "Salsa Dick", seed: 3, finish: 4 },
      { franchise: "Magoo",      seed: 5, finish: 5 },
      { franchise: "Kam",       seed: 4, finish: 6 },
    ],
    standings: [
      { franchise: "Trust",      rec: "7-6-0",  pf: 1224.98, pa: 1141.20 },
      { franchise: "Vidz",       rec: "10-3-0", pf: 1365.32, pa: 1154.08 },
      { franchise: "Biceps Inc", rec: "8-5-0",  pf: 1427.96, pa: 1334.18 },
      { franchise: "Salsa Dick", rec: "8-5-0",  pf: 1330.24, pa: 1269.28 },
      { franchise: "Magoo",      rec: "7-6-0",  pf: 1255.20, pa: 1127.30 },
      { franchise: "Kam",       rec: "8-5-0",  pf: 1374.98, pa: 1222.98 },
      { franchise: "Boomer",     rec: "6-7-0",  pf: 1176.44, pa: 1235.20 },
      { franchise: "Devany",     rec: "6-7-0",  pf: 1254.62, pa: 1204.96 },
      { franchise: "Fritz",      rec: "4-9-0",  pf: 1178.50, pa: 1295.24 },
      { franchise: "DDC",        rec: "4-9-0",  pf: 1204.14, pa: 1437.18 },
      { franchise: "Sherlock",   rec: "6-7-0",  pf: 1162.04, pa: 1343.90 },
      { franchise: "Tino", rec: "4-9-0",  pf: 1073.18, pa: 1262.10 },
    ],
  },
  {
    year: 2015, champion: "Kam", runnerUp: "Devany", third: "Salsa Dick",
    playoffs: [
      { franchise: "Kam",       seed: 2, finish: 1 },
      { franchise: "Devany",     seed: 5, finish: 2 },
      { franchise: "Salsa Dick", seed: 1, finish: 3 },
      { franchise: "Tino", seed: 6, finish: 4 },
      { franchise: "Vidz",       seed: 3, finish: 5 },
      { franchise: "DDC",        seed: 4, finish: 6 },
    ],
    standings: [
      { franchise: "Kam",       rec: "7-6-0",  pf: 1200.16, pa: 1202.54 },
      { franchise: "Devany",     rec: "7-6-0",  pf: 1330.76, pa: 1286.22 },
      { franchise: "Salsa Dick", rec: "10-3-0", pf: 1398.52, pa: 1231.28 },
      { franchise: "Tino", rec: "7-6-0",  pf: 1197.66, pa: 1238.20 },
      { franchise: "DDC",        rec: "10-3-0", pf: 1396.86, pa: 1236.38 },
      { franchise: "Vidz",       rec: "9-4-0",  pf: 1281.66, pa: 1254.88 },
      { franchise: "Fritz",      rec: "5-8-0",  pf: 1288.06, pa: 1305.66 },
      { franchise: "Biceps Inc", rec: "2-11-0", pf: 1101.32, pa: 1394.16 },
      { franchise: "Sherlock",   rec: "6-7-0",  pf: 1150.22, pa: 1134.62 },
      { franchise: "Magoo",      rec: "6-7-0",  pf: 1234.14, pa: 1265.24 },
      { franchise: "Trust",      rec: "6-7-0",  pf: 1152.66, pa: 1077.06 },
      { franchise: "Boomer",     rec: "3-10-0", pf: 1158.86, pa: 1264.64 },
    ],
  },
  {
    year: 2014, champion: "Magoo", runnerUp: "Kam", third: "Sherlock",
    playoffs: [
      { franchise: "Magoo",      seed: 1, finish: 1 },
      { franchise: "Kam",       seed: 2, finish: 2 },
      { franchise: "Sherlock",   seed: 6, finish: 3 },
      { franchise: "Vidz",       seed: 5, finish: 4 },
      { franchise: "Fritz",      seed: 4, finish: 5 },
      { franchise: "Salsa Dick", seed: 3, finish: 6 },
    ],
    standings: [
      { franchise: "Magoo",      rec: "12-1-0", pf: 1494.52, pa: 1054.30 },
      { franchise: "Kam",       rec: "7-6-0",  pf: 1372.64, pa: 1243.10 },
      { franchise: "Sherlock",   rec: "6-7-0",  pf: 1341.70, pa: 1198.90 },
      { franchise: "Vidz",       rec: "6-7-0",  pf: 1355.28, pa: 1339.52 },
      { franchise: "Salsa Dick", rec: "12-1-0", pf: 1459.64, pa: 1162.06 },
      { franchise: "Fritz",      rec: "7-6-0",  pf: 1269.66, pa: 1258.26 },
      { franchise: "Trust",      rec: "6-7-0",  pf: 1084.80, pa: 1179.82 },
      { franchise: "Tino", rec: "3-10-0", pf: 1034.16, pa: 1256.96 },
      { franchise: "Boomer",     rec: "4-9-0",  pf: 1143.84, pa: 1259.06 },
      { franchise: "DDC",        rec: "6-7-0",  pf: 1260.16, pa: 1261.34 },
      { franchise: "Devany",     rec: "3-10-0", pf: 892.74,  pa: 1320.18 },
      { franchise: "Biceps Inc", rec: "6-7-0",  pf: 1304.10, pa: 1479.74 },
    ],
  },
  {
    year: 2013, champion: "Kam", runnerUp: "Fritz", third: "Tino",
    playoffs: [
      { franchise: "Kam",       seed: 3, finish: 1 },
      { franchise: "Fritz",      seed: 1, finish: 2 },
      { franchise: "Tino", seed: 4, finish: 3 },
      { franchise: "Boomer",     seed: 6, finish: 4 },
      { franchise: "Biceps Inc", seed: 5, finish: 5 },
      { franchise: "Magoo",      seed: 2, finish: 6 },
    ],
    standings: [
      { franchise: "Kam",       rec: "9-4-0",  pf: 1465, pa: 1307 },
      { franchise: "Fritz",      rec: "10-3-0", pf: 1268, pa: 1130 },
      { franchise: "Tino", rec: "7-5-1",  pf: 1247, pa: 1142 },
      { franchise: "Magoo",      rec: "7-5-1",  pf: 1209, pa: 1073 },
      { franchise: "Biceps Inc", rec: "7-6-0",  pf: 1212, pa: 1126 },
      { franchise: "Boomer",     rec: "6-5-2",  pf: 1132, pa: 1215 },
      { franchise: "Sherlock",   rec: "5-8-0",  pf: 1257, pa: 1389 },
      { franchise: "Trust",      rec: "6-7-0",  pf: 1199, pa: 1130 },
      { franchise: "Vidz",       rec: "4-8-1",  pf: 1056, pa: 1302 },
      { franchise: "Salsa Dick", rec: "6-6-1",  pf: 1185, pa: 1129 },
      { franchise: "Devany",     rec: "3-10-0", pf: 984,  pa: 1090 },
      { franchise: "DDC",        rec: "5-8-0",  pf: 1068, pa: 1249 },
    ],
  },
  {
    year: 2012, champion: "Vidz", runnerUp: "Boomer", third: "Kam",
    playoffs: [
      { franchise: "Vidz",       seed: 5, finish: 1 },
      { franchise: "Boomer",     seed: 2, finish: 2 },
      { franchise: "Kam",       seed: 3, finish: 3 },
      { franchise: "Salizzoni",  seed: 1, finish: 4 },
      { franchise: "Sherlock",   seed: 4, finish: 5 },
      { franchise: "Biceps Inc", seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Vidz",       rec: "7-6-0",  pf: 1219, pa: 1140 },
      { franchise: "Boomer",     rec: "7-6-0",  pf: 1340, pa: 1270 },
      { franchise: "Kam",       rec: "9-4-0",  pf: 1329, pa: 1024 },
      { franchise: "Salizzoni",  rec: "10-3-0", pf: 1350, pa: 1171 },
      { franchise: "Sherlock",   rec: "8-5-0",  pf: 1204, pa: 1135 },
      { franchise: "Biceps Inc", rec: "7-6-0",  pf: 1149, pa: 1211 },
      { franchise: "Fritz",      rec: "6-7-0",  pf: 1226, pa: 1198 },
      { franchise: "Salsa Dick", rec: "6-7-0",  pf: 1202, pa: 1293 },
      { franchise: "Mysliwiec",  rec: "5-8-0",  pf: 1007, pa: 1226 },
      { franchise: "Fraga",      rec: "3-10-0", pf: 1045, pa: 1186 },
      { franchise: "Magoo",      rec: "4-9-0",  pf: 1078, pa: 1242 },
      { franchise: "WLopez",     rec: "6-7-0",  pf: 1103, pa: 1156 },
    ],
  },
  {
    year: 2011, champion: "Salizzoni", runnerUp: "Salsa Dick", third: "Vidz",
    note: "Inaugural season",
    playoffs: [
      { franchise: "Salizzoni",  seed: 5, finish: 1 },
      { franchise: "Salsa Dick", seed: 3, finish: 2 },
      { franchise: "Vidz",       seed: 1, finish: 3 },
      { franchise: "Magoo",      seed: 4, finish: 4 },
      { franchise: "Hatala",     seed: 2, finish: 5 },
      { franchise: "Sherlock",   seed: 6, finish: 6 },
    ],
    standings: [
      { franchise: "Vidz",       rec: "11-2-0", pf: 1316, pa: 1021 },
      { franchise: "Hatala",     rec: "9-4-0",  pf: 1150, pa: 1028 },
      { franchise: "Salsa Dick", rec: "9-4-0",  pf: 1263, pa: 1123 },
      { franchise: "Magoo",      rec: "9-4-0",  pf: 1219, pa: 1073 },
      { franchise: "Salizzoni",  rec: "7-6-0",  pf: 1117, pa: 1176 },
      { franchise: "Sherlock",   rec: "6-7-0",  pf: 1143, pa: 1054 },
      { franchise: "Biceps Inc", rec: "5-7-1",  pf: 1097, pa: 1168 },
      { franchise: "Kam",       rec: "6-7-0",  pf: 1088, pa: 1158 },
      { franchise: "Boomer",     rec: "4-8-1",  pf: 1174, pa: 1231 },
      { franchise: "Herman",     rec: "5-8-0",  pf: 1078, pa: 1147 },
      { franchise: "Pedersen",   rec: "3-10-0", pf: 958,  pa: 1138 },
      { franchise: "Fraga",      rec: "3-10-0", pf: 992,  pa: 1278 },
    ],
  },
];

// ── TRADE HISTORY ──
// Add trades here as you remember them.
export const TRADES = [
  {
    id: "trade_002", year: 2025, week: 11,
    sideA: { franchise: "Brian Company", gave: ["Courtland Sutton"], received: ["Jordan Addison"] },
    sideB: { franchise: "Salsa Hips", gave: ["Jordan Addison"], received: ["Courtland Sutton"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_001", year: 2025, week: 11,
    sideA: { franchise: "ASS N Onionz", gave: ["Caleb Williams", "DJ Moore", "David Montgomery"], received: ["Mark Andrews", "Ja'Marr Chase"] },
    sideB: { franchise: "King's Landing", gave: ["Mark Andrews", "Ja'Marr Chase"], received: ["Caleb Williams", "DJ Moore", "David Montgomery"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_003", year: 2025, week: 5,
    sideA: { franchise: "TheOneWhoGoesBumpIntheNight", gave: ["Omarion Hampton"], received: ["Ja'Marr Chase"] },
    sideB: { franchise: "Salsa Hips", gave: ["Ja'Marr Chase"], received: ["Omarion Hampton"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_007", year: 2024, week: 11,
    sideA: { franchise: "Here Comes the Boom", gave: ["Cade Otton"], received: ["DeVonta Smith"] },
    sideB: { franchise: "Who's Yah Daddy", gave: ["DeVonta Smith"], received: ["Cade Otton"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_006", year: 2024, week: 10,
    sideA: { franchise: "El Problemo CNDB", gave: ["Jonathon Brooks", "Deebo Samuel Sr."], received: ["DK Metcalf", "Jaylen Warren"] },
    sideB: { franchise: "Salsa Hips", gave: ["DK Metcalf", "Jaylen Warren"], received: ["Jonathon Brooks", "Deebo Samuel Sr."] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_005", year: 2024, week: 8,
    sideA: { franchise: "El Problemo CNDB", gave: ["Marvin Harrison Jr.", "Aaron Jones"], received: ["Bijan Robinson"] },
    sideB: { franchise: "Swoly Moly", gave: ["Bijan Robinson"], received: ["Marvin Harrison Jr.", "Aaron Jones"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_004", year: 2024, week: 7,
    sideA: { franchise: "TestStripsarefortheGays", gave: ["Brian Robinson Jr."], received: ["Raheem Mostert", "Sam LaPorta"] },
    sideB: { franchise: "Salsa Hips", gave: ["Raheem Mostert", "Sam LaPorta"], received: ["Brian Robinson Jr."] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_009", year: 2023, week: 12,
    sideA: { franchise: "El Problemo CNDB", gave: ["Russell Wilson"], received: ["Zack Moss"] },
    sideB: { franchise: "Salsa Hips", gave: ["Zack Moss"], received: ["Russell Wilson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_010", year: 2023, week: 11,
    sideA: { franchise: "Salsa Hips", gave: ["Courtland Sutton"], received: ["Dalton Schultz"] },
    sideB: { franchise: "Local Legend", gave: ["Dalton Schultz"], received: ["Courtland Sutton"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_011", year: 2023, week: 10,
    sideA: { franchise: "Biceps Inc", gave: ["Zay Flowers"], received: ["Taysom Hill", "Dalton Schultz"] },
    sideB: { franchise: "Local Legend", gave: ["Taysom Hill", "Dalton Schultz"], received: ["Zay Flowers"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_012", year: 2023, week: 9,
    sideA: { franchise: "Biceps Inc", gave: ["Breece Hall"], received: ["CeeDee Lamb"] },
    sideB: { franchise: "Brian Company", gave: ["CeeDee Lamb"], received: ["Breece Hall"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_016", year: 2023, week: 9,
    sideA: { franchise: "Salsa Hips", gave: ["Dalton Kincaid", "Diontae Johnson"], received: ["DK Metcalf"] },
    sideB: { franchise: "Brian Company", gave: ["DK Metcalf"], received: ["Dalton Kincaid", "Diontae Johnson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_013", year: 2023, week: 6,
    sideA: { franchise: "Biceps Inc", gave: ["Michael Pittman Jr."], received: ["Zay Flowers"] },
    sideB: { franchise: "Salsa Hips", gave: ["Zay Flowers"], received: ["Michael Pittman Jr."] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_014", year: 2023, week: 3,
    sideA: { franchise: "Mac Champ Champ Stacks", gave: ["Courtland Sutton"], received: ["Gus Edwards"] },
    sideB: { franchise: "Salsa Hips", gave: ["Gus Edwards"], received: ["Courtland Sutton"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_015", year: 2023, week: 2,
    sideA: { franchise: "Who's Yah Daddy", gave: ["Elijah Mitchell"], received: ["Michael Thomas"] },
    sideB: { franchise: "Salsa Hips", gave: ["Michael Thomas"], received: ["Elijah Mitchell"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_025", year: 2022, week: 10,
    sideA: { franchise: "Stairway To Seven", gave: ["Allen Lazard", "Zach Ertz", "Justin Fields", "Cam Akers"], received: ["Jonathan Taylor", "Deon Jackson"] },
    sideB: { franchise: "The Replacements", gave: ["Jonathan Taylor", "Deon Jackson"], received: ["Allen Lazard", "Zach Ertz", "Justin Fields", "Cam Akers"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_026", year: 2022, week: 9,
    sideA: { franchise: "Brian Company", gave: ["AJ Dillon", "Garrett Wilson"], received: ["DeVonta Smith", "Michael Thomas"] },
    sideB: { franchise: "Mister Unliiiiimited", gave: ["DeVonta Smith", "Michael Thomas"], received: ["AJ Dillon", "Garrett Wilson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_027", year: 2021, week: 11,
    sideA: { franchise: "Teezus Walks", gave: ["AJ Dillon", "Ja'Marr Chase", "Joe Burrow"], received: ["Derrick Henry", "Terry McLaurin", "Patrick Mahomes"] },
    sideB: { franchise: "Conor N Da Boyz", gave: ["Derrick Henry", "Terry McLaurin", "Patrick Mahomes"], received: ["AJ Dillon", "Ja'Marr Chase", "Joe Burrow"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_028", year: 2021, week: 10,
    sideA: { franchise: "Kitty CoVidz", gave: ["Ezekiel Elliott", "Lamar Jackson", "Tony Pollard"], received: ["Kyler Murray", "Cordarrelle Patterson", "Myles Gaskin", "CeeDee Lamb"] },
    sideB: { franchise: "Salsa Champ", gave: ["Kyler Murray", "Cordarrelle Patterson", "Myles Gaskin", "CeeDee Lamb"], received: ["Ezekiel Elliott", "Lamar Jackson", "Tony Pollard"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_030", year: 2021, week: 10,
    sideA: { franchise: "Salsa Champ", gave: ["Adrian Peterson"], received: ["Odell Beckham Jr."] },
    sideB: { franchise: "Conor N Da Boyz", gave: ["Odell Beckham Jr."], received: ["Adrian Peterson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_031", year: 2021, week: 9,
    sideA: { franchise: "Christian Mingle", gave: ["George Kittle", "Christian McCaffrey"], received: ["Jakobi Meyers", "Cardinals D/ST", "Chris Godwin", "Darrell Henderson Jr."] },
    sideB: { franchise: "Teezus Walks", gave: ["Jakobi Meyers", "Cardinals D/ST", "Chris Godwin", "Darrell Henderson Jr."], received: ["George Kittle", "Christian McCaffrey"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_051", year: 2021, week: 7,
    sideA: { franchise: "Stairway To Seven", gave: ["Amari Cooper", "Kyler Murray"], received: ["Calvin Ridley", "Michael Carter"] },
    sideB: { franchise: "Salsa Champ", gave: ["Calvin Ridley", "Michael Carter"], received: ["Amari Cooper", "Kyler Murray"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_032", year: 2021, week: 7,
    sideA: { franchise: "Conor N Da Boyz", gave: ["James Conner"], received: ["Dalton Schultz"] },
    sideB: { franchise: "Salsa Champ", gave: ["Dalton Schultz"], received: ["James Conner"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_033", year: 2020, week: 12,
    sideA: { franchise: "Mac Stacks", gave: ["Antonio Brown", "DeVante Parker", "Tony Pollard"], received: ["Clyde Edwards-Helaire", "JuJu Smith-Schuster", "Allen Lazard"] },
    sideB: { franchise: "Inflatable Biceps", gave: ["Clyde Edwards-Helaire", "JuJu Smith-Schuster", "Allen Lazard"], received: ["Antonio Brown", "DeVante Parker", "Tony Pollard"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_034", year: 2020, week: 12,
    sideA: { franchise: "Kitty CoVidz", gave: ["Aaron Rodgers"], received: ["Lamar Jackson", "Darrell Henderson Jr.", "Tee Higgins"] },
    sideB: { franchise: "Inflatable Biceps", gave: ["Lamar Jackson", "Darrell Henderson Jr.", "Tee Higgins"], received: ["Aaron Rodgers"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_035", year: 2020, week: 11,
    sideA: { franchise: "Stairway To Seven", gave: ["Tee Higgins", "Ronald Jones II", "Damien Harris"], received: ["Aaron Jones"] },
    sideB: { franchise: "Inflatable Biceps", gave: ["Aaron Jones"], received: ["Tee Higgins", "Ronald Jones II", "Damien Harris"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_036", year: 2020, week: 10,
    sideA: { franchise: "The Braintrust", gave: ["Zack Moss"], received: ["Brandin Cooks"] },
    sideB: { franchise: "Salsa Dick", gave: ["Brandin Cooks"], received: ["Zack Moss"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_044", year: 2020, week: 10,
    sideA: { franchise: "Stairway To Seven", gave: ["Josh Allen", "DJ Moore"], received: ["DJ Chark Jr."] },
    sideB: { franchise: "The Braintrust", gave: ["DJ Chark Jr."], received: ["Josh Allen", "DJ Moore"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_045", year: 2020, week: 10,
    sideA: { franchise: "Inflatable Biceps", gave: ["Clyde Edwards-Helaire", "JuJu Smith-Schuster", "Noah Fant"], received: ["Michael Thomas", "Eric Ebron"] },
    sideB: { franchise: "Tomasz Fantasy Football Team", gave: ["Michael Thomas", "Eric Ebron"], received: ["Clyde Edwards-Helaire", "JuJu Smith-Schuster", "Noah Fant"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_038", year: 2019, week: 9,
    sideA: { franchise: "King Fritty", gave: ["Mohamed Sanu"], received: ["James White", "Sammy Watkins"] },
    sideB: { franchise: "Biceps Inc", gave: ["James White", "Sammy Watkins"], received: ["Mohamed Sanu"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_037", year: 2019, week: 9,
    sideA: { franchise: "Mac Stacks", gave: ["Odell Beckham Jr."], received: ["Austin Hooper"] },
    sideB: { franchise: "Stairway To Seven", gave: ["Austin Hooper"], received: ["Odell Beckham Jr."] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_040", year: 2019, week: 9,
    sideA: { franchise: "Trash Run", gave: ["Gardner Minshew II"], received: ["Chris Thompson"] },
    sideB: { franchise: "Salsa Dick", gave: ["Chris Thompson"], received: ["Gardner Minshew II"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_042", year: 2019, week: 6,
    sideA: { franchise: "Biceps Inc", gave: ["Derrick Henry", "T.Y. Hilton", "Marvin Jones Jr."], received: ["Alvin Kamara", "Calvin Ridley"] },
    sideB: { franchise: "Warlord Vein N Da Boyz", gave: ["Alvin Kamara", "Calvin Ridley"], received: ["Derrick Henry", "T.Y. Hilton", "Marvin Jones Jr."] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_041", year: 2019, week: 4,
    sideA: { franchise: "Ground and Pound", gave: ["Demarcus Robinson"], received: ["Mike Williams"] },
    sideB: { franchise: "Trash Run", gave: ["Mike Williams"], received: ["Demarcus Robinson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_039", year: 2019, week: 4,
    sideA: { franchise: "Trash Run", gave: ["Greg Olsen", "Marquise Brown"], received: ["Joe Mixon"] },
    sideB: { franchise: "Warlord Vein N Da Boyz", gave: ["Joe Mixon"], received: ["Greg Olsen", "Marquise Brown"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_043", year: 2019, week: 3,
    sideA: { franchise: "Brian Company", gave: ["Devonta Freeman"], received: ["Cooper Kupp"] },
    sideB: { franchise: "Salsa Dick", gave: ["Cooper Kupp"], received: ["Devonta Freeman"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_046", year: 2018, week: 10,
    sideA: { franchise: "Salsa Dick", gave: ["Eric Ebron"], received: ["Ben Roethlisberger"] },
    sideB: { franchise: "Here Comes the Boom", gave: ["Ben Roethlisberger"], received: ["Eric Ebron"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_047", year: 2018, week: 9,
    sideA: { franchise: "GangGreen The Kid", gave: ["Alshon Jeffery"], received: ["T.Y. Hilton", "Kenyan Drake"] },
    sideB: { franchise: "Ground and Pound", gave: ["T.Y. Hilton", "Kenyan Drake"], received: ["Alshon Jeffery"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_048", year: 2018, week: 9,
    sideA: { franchise: "GangGreen The Kid", gave: ["Jets D/ST"], received: ["Eagles D/ST"] },
    sideB: { franchise: "KHunt Pounders", gave: ["Eagles D/ST"], received: ["Jets D/ST"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_049", year: 2018, week: 9,
    sideA: { franchise: "Warlord Vein N Da Boyz", gave: ["Emmanuel Sanders", "Tevin Coleman"], received: ["Odell Beckham Jr.", "Austin Hooper"] },
    sideB: { franchise: "Stairway To Seven", gave: ["Odell Beckham Jr.", "Austin Hooper"], received: ["Emmanuel Sanders", "Tevin Coleman"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_054", year: 2018, week: 5,
    sideA: { franchise: "Ground and Pound", gave: ["Rex Burkhead", "John Brown"], received: ["Kenyan Drake", "Larry Fitzgerald"] },
    sideB: { franchise: "Here Comes the Boom", gave: ["Kenyan Drake", "Larry Fitzgerald"], received: ["Rex Burkhead", "John Brown"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_053", year: 2018, week: 4,
    sideA: { franchise: "Warlord Vein N Da Boyz", gave: ["Sammy Watkins", "James White"], received: ["DeSean Jackson", "Jared Goff"] },
    sideB: { franchise: "Salsa Dick", gave: ["DeSean Jackson", "Jared Goff"], received: ["Sammy Watkins", "James White"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_052", year: 2018, week: 3,
    sideA: { franchise: "Biceps Inc", gave: ["Rex Burkhead"], received: ["O.J. Howard"] },
    sideB: { franchise: "Ground and Pound", gave: ["O.J. Howard"], received: ["Rex Burkhead"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_050", year: 2018, week: 0,
    sideA: { franchise: "Ground and Pound", gave: ["Peyton Barber"], received: ["Jordan Reed"] },
    sideB: { franchise: "Stairway To Gay", gave: ["Jordan Reed"], received: ["Peyton Barber"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_055", year: 2017, week: 11,
    sideA: { franchise: "Stairway To Seven", gave: ["Ben Roethlisberger"], received: ["Ameer Abdullah"] },
    sideB: { franchise: "Band of Gypsies", gave: ["Ameer Abdullah"], received: ["Ben Roethlisberger"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_056", year: 2017, week: 10,
    sideA: { franchise: "Cheeseburger Eddie", gave: ["DeVante Parker"], received: ["Kyle Rudolph"] },
    sideB: { franchise: "Ground and Pound", gave: ["Kyle Rudolph"], received: ["DeVante Parker"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_057", year: 2017, week: 9,
    sideA: { franchise: "The Braintrust", gave: ["Jake Elliott", "D'Onta Foreman"], received: ["Vernon Davis", "Ted Ginn Jr."] },
    sideB: { franchise: "Stairway To Seven", gave: ["Vernon Davis", "Ted Ginn Jr."], received: ["Jake Elliott", "D'Onta Foreman"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_058", year: 2017, week: 9,
    sideA: { franchise: "Ground and Pound", gave: ["Jamison Crowder", "Dion Lewis"], received: ["Hunter Henry"] },
    sideB: { franchise: "Cheeseburger Eddie", gave: ["Hunter Henry"], received: ["Jamison Crowder", "Dion Lewis"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_059", year: 2017, week: 8,
    sideA: { franchise: "THANKGOD ALMITY FREEman AT LAST", gave: ["Jonathan Stewart"], received: ["Robbie Gould"] },
    sideB: { franchise: "Stairway To Seven", gave: ["Robbie Gould"], received: ["Jonathan Stewart"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_060", year: 2017, week: 7,
    sideA: { franchise: "Here Comes the Boom", gave: ["Alex Smith"], received: ["DeSean Jackson", "Matthew Stafford"] },
    sideB: { franchise: "THANKGOD ALMITY FREEman AT LAST", gave: ["DeSean Jackson", "Matthew Stafford"], received: ["Alex Smith"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_061", year: 2017, week: 7,
    sideA: { franchise: "Here Comes the Boom", gave: ["Dez Bryant"], received: ["Chris Hogan"] },
    sideB: { franchise: "Salsa Dick", gave: ["Chris Hogan"], received: ["Dez Bryant"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_062", year: 2017, week: 7,
    sideA: { franchise: "GangGreen The Kid", gave: ["Mark Ingram"], received: ["Demaryius Thomas", "Cam Newton"] },
    sideB: { franchise: "Salsa Dick", gave: ["Demaryius Thomas", "Cam Newton"], received: ["Mark Ingram"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_063", year: 2017, week: 7,
    sideA: { franchise: "Stairway To Seven", gave: ["Alvin Kamara", "Jimmy Graham"], received: ["Zach Ertz"] },
    sideB: { franchise: "Band of Gypsies", gave: ["Zach Ertz"], received: ["Alvin Kamara", "Jimmy Graham"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_064", year: 2017, week: 7,
    sideA: { franchise: "Cheeseburger Eddie", gave: ["Keenan Allen"], received: ["Derrick Henry"] },
    sideB: { franchise: "Fritz Zilla", gave: ["Derrick Henry"], received: ["Keenan Allen"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_065", year: 2017, week: 7,
    sideA: { franchise: "Band of Gypsies", gave: ["Matt Forte"], received: ["Sterling Shepard", "Jesse James"] },
    sideB: { franchise: "GangGreen The Kid", gave: ["Sterling Shepard", "Jesse James"], received: ["Matt Forte"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_066", year: 2017, week: 7,
    sideA: { franchise: "Stairway To Seven", gave: ["Adrian Peterson"], received: ["Doug Baldwin"] },
    sideB: { franchise: "Here Comes the Boom", gave: ["Doug Baldwin"], received: ["Adrian Peterson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_067", year: 2017, week: 6,
    sideA: { franchise: "Conor N Da Boyz", gave: ["Jarvis Landry"], received: ["Sammy Watkins"] },
    sideB: { franchise: "THANKGOD ALMITY FREEman AT LAST", gave: ["Sammy Watkins"], received: ["Jarvis Landry"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_068", year: 2017, week: 6,
    sideA: { franchise: "Here Comes the Boom", gave: ["Jamison Crowder", "LeSean McCoy"], received: ["C.J. Anderson", "Doug Baldwin"] },
    sideB: { franchise: "Ground and Pound", gave: ["C.J. Anderson", "Doug Baldwin"], received: ["Jamison Crowder", "LeSean McCoy"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_069", year: 2017, week: 5,
    sideA: { franchise: "Mac Stacks", gave: ["Eddie Lacy"], received: ["Martavis Bryant"] },
    sideB: { franchise: "Biceps Inc", gave: ["Martavis Bryant"], received: ["Eddie Lacy"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_070", year: 2017, week: 4,
    sideA: { franchise: "Ground and Pound", gave: ["Chris Carson", "Amari Cooper"], received: ["Jordy Nelson"] },
    sideB: { franchise: "The Braintrust", gave: ["Jordy Nelson"], received: ["Chris Carson", "Amari Cooper"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_071", year: 2016, week: 12,
    sideA: { franchise: "Conor N Da Boyz", gave: ["Latavius Murray"], received: ["Matt Ryan"] },
    sideB: { franchise: "Salsa Dick", gave: ["Matt Ryan"], received: ["Latavius Murray"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_072", year: 2016, week: 10,
    sideA: { franchise: "The Braintrust", gave: ["Antonio Gates"], received: ["Robert Kelley"] },
    sideB: { franchise: "Ground and Pound", gave: ["Robert Kelley"], received: ["Antonio Gates"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_073", year: 2016, week: 8,
    sideA: { franchise: "GangGreen The Kid", gave: ["Russell Wilson", "Matt Forte"], received: ["Matt Asiata", "Aaron Rodgers"] },
    sideB: { franchise: "Gronk N Da Boyz", gave: ["Matt Asiata", "Aaron Rodgers"], received: ["Russell Wilson", "Matt Forte"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_074", year: 2016, week: 7,
    sideA: { franchise: "Biceps Inc", gave: ["DeMarco Murray", "Marvin Jones", "Demaryius Thomas"], received: ["David Johnson", "Julian Edelman", "Michael Thomas"] },
    sideB: { franchise: "Brian Company", gave: ["David Johnson", "Julian Edelman", "Michael Thomas"], received: ["DeMarco Murray", "Marvin Jones", "Demaryius Thomas"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_075", year: 2016, week: 4,
    sideA: { franchise: "Ground and Pound", gave: ["Devontae Booker", "Chris Hogan"], received: ["DeSean Jackson"] },
    sideB: { franchise: "Conor N Da Boyz", gave: ["DeSean Jackson"], received: ["Devontae Booker", "Chris Hogan"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_076", year: 2016, week: 1,
    sideA: { franchise: "Here Comes the Boom", gave: ["Eric Ebron"], received: ["Terrance West"] },
    sideB: { franchise: "Ground and Pound", gave: ["Terrance West"], received: ["Eric Ebron"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_019", year: 2015, week: 11,
    sideA: { franchise: "The Braintrust", gave: ["Larry Fitzgerald"], received: ["Justin Forsett", "Rishard Matthews"] },
    sideB: { franchise: "Salsa Dick", gave: ["Justin Forsett", "Rishard Matthews"], received: ["Larry Fitzgerald"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_018", year: 2015, week: 10,
    sideA: { franchise: "Here Comes the Boom", gave: ["Cam Newton"], received: ["Russell Wilson", "Jonathan Stewart", "Karlos Williams"] },
    sideB: { franchise: "Fritz Zilla", gave: ["Russell Wilson", "Jonathan Stewart", "Karlos Williams"], received: ["Cam Newton"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_021", year: 2015, week: 10,
    sideA: { franchise: "Bad Comedian Eli Manning", gave: ["Eli Manning"], received: ["Davante Adams"] },
    sideB: { franchise: "Mac Stacks", gave: ["Davante Adams"], received: ["Eli Manning"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_024", year: 2015, week: 9,
    sideA: { franchise: "ConorNtheBoyz", gave: ["Giovani Bernard"], received: ["Ryan Mathews"] },
    sideB: { franchise: "Stairway to Evans", gave: ["Ryan Mathews"], received: ["Giovani Bernard"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_017", year: 2015, week: 9,
    sideA: { franchise: "Snitches Get Switches", gave: ["Marvin Jones", "Adrian Peterson", "Eric Ebron"], received: ["Keenan Allen", "Gary Barnidge", "DeMarco Murray"] },
    sideB: { franchise: "ConorNtheBoyz", gave: ["Keenan Allen", "Gary Barnidge", "DeMarco Murray"], received: ["Marvin Jones", "Adrian Peterson", "Eric Ebron"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_020", year: 2015, week: 8,
    sideA: { franchise: "Fritz Zilla", gave: ["Jordan Reed"], received: ["Jordan Cameron"] },
    sideB: { franchise: "Stairway To Seven", gave: ["Jordan Cameron"], received: ["Jordan Reed"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_023", year: 2015, week: 7,
    sideA: { franchise: "GangGreen The Kid", gave: ["Calvin Johnson"], received: ["Arian Foster"] },
    sideB: { franchise: "Biceps Inc", gave: ["Arian Foster"], received: ["Calvin Johnson"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_022", year: 2015, week: 5,
    sideA: { franchise: "GangGreen The Kid", gave: ["Andre Ellington"], received: ["Eric Decker"] },
    sideB: { franchise: "Ground and Pound", gave: ["Eric Decker"], received: ["Andre Ellington"] },
    winner: null, shame: false, verdict: "",
  },
  {
    id: "trade_008", year: 2015, week: 0,
    sideA: { franchise: "Ground and Pound", gave: ["Jason Witten", "Jarvis Landry"], received: ["Greg Olsen"] },
    sideB: { franchise: "Here Comes the Boom", gave: ["Greg Olsen"], received: ["Jason Witten", "Jarvis Landry"] },
    winner: null, shame: false, verdict: "",
  },
];
