// ─────────────────────────────────────────────
// DRAFT DATA — 2018–2025
// To update: add picks to the relevant year's array,
// or add a new season object at the end.
// ─────────────────────────────────────────────

export const DRAFTS = [
  {
    year: 2018, rounds: 15, status: "complete",
    picks: [
      { overall: 1,   round: 1,  pick: 1,  franchise: "Vidz",      player: "Le'Veon Bell",         pos: "RB", keeper: false },
      { overall: 2,   round: 1,  pick: 2,  franchise: "Magoo",     player: "Ezekiel Elliott",       pos: "RB", keeper: false },
      { overall: 3,   round: 1,  pick: 3,  franchise: "DDC",       player: "David Johnson",         pos: "RB", keeper: false },
      { overall: 4,   round: 1,  pick: 4,  franchise: "Sherlock",  player: "Saquon Barkley",        pos: "RB", keeper: false },
      { overall: 5,   round: 1,  pick: 5,  franchise: "Salsa Dick",player: "Leonard Fournette",     pos: "RB", keeper: false },
      { overall: 6,   round: 1,  pick: 6,  franchise: "Biceps Inc",player: "Antonio Brown",         pos: "WR", keeper: false },
      { overall: 7,   round: 1,  pick: 7,  franchise: "Boomer",    player: "Dalvin Cook",           pos: "RB", keeper: false },
      { overall: 8,   round: 1,  pick: 8,  franchise: "Devany",    player: "Melvin Gordon III",     pos: "RB", keeper: false },
      { overall: 9,   round: 1,  pick: 9,  franchise: "Tino",      player: "Todd Gurley II",        pos: "RB", keeper: true  },
      { overall: 10,  round: 1,  pick: 10, franchise: "Fritz",     player: "Julio Jones",           pos: "WR", keeper: false },
      { overall: 11,  round: 1,  pick: 11, franchise: "Kam",       player: "Odell Beckham Jr.",     pos: "WR", keeper: false },
      { overall: 12,  round: 1,  pick: 12, franchise: "Trust",     player: "Devonta Freeman",       pos: "RB", keeper: false },
      { overall: 13,  round: 2,  pick: 1,  franchise: "Vidz",      player: "Mike Evans",            pos: "WR", keeper: false },
      { overall: 14,  round: 2,  pick: 2,  franchise: "Magoo",     player: "A.J. Green",            pos: "WR", keeper: false },
      { overall: 15,  round: 2,  pick: 3,  franchise: "DDC",       player: "T.Y. Hilton",           pos: "WR", keeper: false },
      { overall: 16,  round: 2,  pick: 4,  franchise: "Sherlock",  player: "Alex Collins",          pos: "RB", keeper: false },
      { overall: 17,  round: 2,  pick: 5,  franchise: "Salsa Dick",player: "Keenan Allen",          pos: "WR", keeper: false },
      { overall: 18,  round: 2,  pick: 6,  franchise: "Biceps Inc",player: "Davante Adams",         pos: "WR", keeper: false },
      { overall: 19,  round: 2,  pick: 7,  franchise: "Boomer",    player: "Joe Mixon",             pos: "RB", keeper: false },
      { overall: 20,  round: 2,  pick: 8,  franchise: "Devany",    player: "Michael Thomas",        pos: "WR", keeper: false },
      { overall: 21,  round: 2,  pick: 9,  franchise: "Tino",      player: "LeSean McCoy",          pos: "RB", keeper: false },
      { overall: 22,  round: 2,  pick: 10, franchise: "Fritz",     player: "Rob Gronkowski",        pos: "TE", keeper: false },
      { overall: 23,  round: 2,  pick: 11, franchise: "Kam",       player: "Jordan Howard",         pos: "RB", keeper: false },
      { overall: 24,  round: 2,  pick: 12, franchise: "Trust",     player: "Christian McCaffrey",   pos: "RB", keeper: false },
      { overall: 25,  round: 3,  pick: 1,  franchise: "Vidz",      player: "Kareem Hunt",           pos: "RB", keeper: true  },
      { overall: 26,  round: 3,  pick: 2,  franchise: "Magoo",     player: "Amari Cooper",          pos: "WR", keeper: false },
      { overall: 27,  round: 3,  pick: 3,  franchise: "DDC",       player: "Royce Freeman",         pos: "RB", keeper: false },
      { overall: 28,  round: 3,  pick: 4,  franchise: "Sherlock",  player: "Tyreek Hill",           pos: "WR", keeper: false },
      { overall: 29,  round: 3,  pick: 5,  franchise: "Salsa Dick",player: "Jay Ajayi",             pos: "RB", keeper: false },
      { overall: 30,  round: 3,  pick: 6,  franchise: "Biceps Inc",player: "Aaron Rodgers",         pos: "QB", keeper: false },
      { overall: 31,  round: 3,  pick: 7,  franchise: "Boomer",    player: "Kenyan Drake",          pos: "RB", keeper: false },
      { overall: 32,  round: 3,  pick: 8,  franchise: "Devany",    player: "Doug Baldwin",          pos: "WR", keeper: false },
      { overall: 33,  round: 3,  pick: 9,  franchise: "Tino",      player: "Golden Tate",           pos: "WR", keeper: false },
      { overall: 34,  round: 3,  pick: 10, franchise: "Fritz",     player: "Lamar Miller",          pos: "RB", keeper: false },
      { overall: 35,  round: 3,  pick: 11, franchise: "Kam",       player: "DeAndre Hopkins",       pos: "WR", keeper: true  },
      { overall: 36,  round: 3,  pick: 12, franchise: "Trust",     player: "Brandin Cooks",         pos: "WR", keeper: false },
      { overall: 37,  round: 4,  pick: 1,  franchise: "Vidz",      player: "Jarvis Landry",         pos: "WR", keeper: false },
      { overall: 38,  round: 4,  pick: 2,  franchise: "Magoo",     player: "Demaryius Thomas",      pos: "WR", keeper: false },
      { overall: 39,  round: 4,  pick: 3,  franchise: "DDC",       player: "Allen Robinson",        pos: "WR", keeper: false },
      { overall: 40,  round: 4,  pick: 4,  franchise: "Sherlock",  player: "Ronald Jones",          pos: "RB", keeper: false },
      { overall: 41,  round: 4,  pick: 5,  franchise: "Salsa Dick",player: "Tom Brady",             pos: "QB", keeper: false },
      { overall: 42,  round: 4,  pick: 6,  franchise: "Biceps Inc",player: "Marshawn Lynch",        pos: "RB", keeper: false },
      { overall: 43,  round: 4,  pick: 7,  franchise: "Boomer",    player: "Larry Fitzgerald",      pos: "WR", keeper: false },
      { overall: 44,  round: 4,  pick: 8,  franchise: "Devany",    player: "Russell Wilson",        pos: "QB", keeper: false },
      { overall: 45,  round: 4,  pick: 9,  franchise: "Tino",      player: "Alshon Jeffery",        pos: "WR", keeper: false },
      { overall: 46,  round: 4,  pick: 10, franchise: "Fritz",     player: "Cam Newton",            pos: "QB", keeper: false },
      { overall: 47,  round: 4,  pick: 11, franchise: "Kam",       player: "JuJu Smith-Schuster",   pos: "WR", keeper: false },
      { overall: 48,  round: 4,  pick: 12, franchise: "Trust",     player: "Travis Kelce",          pos: "TE", keeper: false },
      { overall: 49,  round: 5,  pick: 1,  franchise: "Vidz",      player: "Robert Woods",          pos: "WR", keeper: false },
      { overall: 50,  round: 5,  pick: 2,  franchise: "Magoo",     player: "Zach Ertz",             pos: "TE", keeper: false },
      { overall: 51,  round: 5,  pick: 3,  franchise: "DDC",       player: "Corey Davis",           pos: "WR", keeper: false },
      { overall: 52,  round: 5,  pick: 4,  franchise: "Sherlock",  player: "Chris Carson",          pos: "RB", keeper: false },
      { overall: 53,  round: 5,  pick: 5,  franchise: "Salsa Dick",player: "Josh Gordon",           pos: "WR", keeper: false },
      { overall: 54,  round: 5,  pick: 6,  franchise: "Biceps Inc",player: "Rex Burkhead",          pos: "RB", keeper: false },
      { overall: 55,  round: 5,  pick: 7,  franchise: "Boomer",    player: "Jimmy Graham",          pos: "TE", keeper: false },
      { overall: 56,  round: 5,  pick: 8,  franchise: "Devany",    player: "Sammy Watkins",         pos: "WR", keeper: false },
      { overall: 57,  round: 5,  pick: 9,  franchise: "Tino",      player: "Michael Crabtree",      pos: "WR", keeper: false },
      { overall: 58,  round: 5,  pick: 10, franchise: "Fritz",     player: "Kerryon Johnson",       pos: "RB", keeper: false },
      { overall: 59,  round: 5,  pick: 11, franchise: "Kam",       player: "Carson Wentz",          pos: "QB", keeper: false },
      { overall: 60,  round: 5,  pick: 12, franchise: "Trust",     player: "Isaiah Crowell",        pos: "RB", keeper: false },
    ]
  },
  {
    year: 2019, rounds: 13, status: "complete",
    picks: [
      { overall: 1,  round: 1, pick: 1,  franchise: "Biceps Inc", player: "Saquon Barkley",       pos: "RB", keeper: false },
      { overall: 2,  round: 1, pick: 2,  franchise: "Boomer",     player: "Ezekiel Elliott",      pos: "RB", keeper: false },
      { overall: 3,  round: 1, pick: 3,  franchise: "Salsa Dick", player: "Alvin Kamara",         pos: "RB", keeper: false },
      { overall: 4,  round: 1, pick: 4,  franchise: "Vidz",       player: "Davante Adams",        pos: "WR", keeper: true  },
      { overall: 5,  round: 1, pick: 5,  franchise: "DDC",        player: "DeAndre Hopkins",      pos: "WR", keeper: true  },
      { overall: 6,  round: 1, pick: 6,  franchise: "Fritz",      player: "Patrick Mahomes",      pos: "QB", keeper: true  },
      { overall: 7,  round: 1, pick: 7,  franchise: "Magoo",      player: "Antonio Brown",        pos: "WR", keeper: false },
      { overall: 8,  round: 1, pick: 8,  franchise: "Trust",      player: "Christian McCaffrey",  pos: "RB", keeper: true  },
      { overall: 9,  round: 1, pick: 9,  franchise: "Tino",       player: "Julio Jones",          pos: "WR", keeper: false },
      { overall: 10, round: 1, pick: 10, franchise: "Kam",        player: "Odell Beckham Jr.",    pos: "WR", keeper: false },
      { overall: 11, round: 1, pick: 11, franchise: "Sorrentino", player: "Todd Gurley II",       pos: "RB", keeper: false },
      { overall: 12, round: 1, pick: 12, franchise: "Sherlock",   player: "Dalvin Cook",          pos: "RB", keeper: false },
    ]
  },
  {
    year: 2020, rounds: 13, status: "complete",
    picks: [
      { overall: 1,  round: 1, pick: 1,  franchise: "Tino",       player: "Christian McCaffrey",  pos: "RB", keeper: true  },
      { overall: 2,  round: 1, pick: 2,  franchise: "Boomer",     player: "Ezekiel Elliott",      pos: "RB", keeper: false },
      { overall: 3,  round: 1, pick: 3,  franchise: "Salsa Dick", player: "Saquon Barkley",       pos: "RB", keeper: false },
      { overall: 4,  round: 1, pick: 4,  franchise: "DDC",        player: "DeAndre Hopkins",      pos: "WR", keeper: true  },
      { overall: 5,  round: 1, pick: 5,  franchise: "Vidz",       player: "Davante Adams",        pos: "WR", keeper: true  },
      { overall: 6,  round: 1, pick: 6,  franchise: "Biceps Inc", player: "Tyreek Hill",          pos: "WR", keeper: false },
      { overall: 7,  round: 1, pick: 7,  franchise: "Trust",      player: "Alvin Kamara",         pos: "RB", keeper: false },
      { overall: 8,  round: 1, pick: 8,  franchise: "Fritz",      player: "Patrick Mahomes",      pos: "QB", keeper: true  },
      { overall: 9,  round: 1, pick: 9,  franchise: "Kam",        player: "Lamar Jackson",        pos: "QB", keeper: false },
      { overall: 10, round: 1, pick: 10, franchise: "Sherlock",   player: "Michael Thomas",       pos: "WR", keeper: false },
      { overall: 11, round: 1, pick: 11, franchise: "Sorrentino", player: "Dalvin Cook",          pos: "RB", keeper: false },
      { overall: 12, round: 1, pick: 12, franchise: "DDC",        player: "Josh Jacobs",          pos: "RB", keeper: false },
    ]
  },
  {
    year: 2021, rounds: 16, status: "complete",
    picks: [
      { overall: 1,  round: 1, pick: 1,  franchise: "Tino",       player: "Christian McCaffrey",  pos: "RB", keeper: true  },
      { overall: 2,  round: 1, pick: 2,  franchise: "Biceps Inc", player: "Tyreek Hill",          pos: "WR", keeper: true  },
      { overall: 3,  round: 1, pick: 3,  franchise: "Boomer",     player: "Davante Adams",        pos: "WR", keeper: false },
      { overall: 4,  round: 1, pick: 4,  franchise: "Magoo",      player: "Alvin Kamara",         pos: "RB", keeper: false },
      { overall: 5,  round: 1, pick: 5,  franchise: "Salsa Dick", player: "Derrick Henry",        pos: "RB", keeper: false },
      { overall: 6,  round: 1, pick: 6,  franchise: "Trust",      player: "Travis Kelce",         pos: "TE", keeper: true  },
      { overall: 7,  round: 1, pick: 7,  franchise: "DDC",        player: "Jonathan Taylor",      pos: "RB", keeper: false },
      { overall: 8,  round: 1, pick: 8,  franchise: "Fritz",      player: "Stefon Diggs",         pos: "WR", keeper: false },
      { overall: 9,  round: 1, pick: 9,  franchise: "Vidz",       player: "Josh Allen",           pos: "QB", keeper: false },
      { overall: 10, round: 1, pick: 10, franchise: "Kam",        player: "Aaron Jones",          pos: "RB", keeper: false },
      { overall: 11, round: 1, pick: 11, franchise: "Sherlock",   player: "Joe Mixon",            pos: "RB", keeper: false },
      { overall: 12, round: 1, pick: 12, franchise: "Sorrentino", player: "Ezekiel Elliott",      pos: "RB", keeper: false },
    ]
  },
  {
    year: 2022, rounds: 14, status: "incomplete",
    picks: [
      { overall: 1,  round: 1, pick: 1,  franchise: "Kam",        player: "Justin Jefferson",     pos: "WR", keeper: true  },
      { overall: 2,  round: 1, pick: 2,  franchise: "Vidz",       player: "Cooper Kupp",          pos: "WR", keeper: false },
      { overall: 3,  round: 1, pick: 3,  franchise: "Biceps Inc", player: "Davante Adams",        pos: "WR", keeper: true  },
      { overall: 4,  round: 1, pick: 4,  franchise: "Boomer",     player: "Ja'Marr Chase",        pos: "WR", keeper: false },
      { overall: 5,  round: 1, pick: 5,  franchise: "Salsa Dick", player: "Christian McCaffrey",  pos: "RB", keeper: false },
      { overall: 6,  round: 1, pick: 6,  franchise: "Trust",      player: "Austin Ekeler",        pos: "RB", keeper: false },
      { overall: 7,  round: 1, pick: 7,  franchise: "Magoo",      player: "CeeDee Lamb",          pos: "WR", keeper: false },
      { overall: 8,  round: 1, pick: 8,  franchise: "DDC",        player: "Tyreek Hill",          pos: "WR", keeper: false },
      { overall: 9,  round: 1, pick: 9,  franchise: "Fritz",      player: "Stefon Diggs",         pos: "WR", keeper: true  },
      { overall: 10, round: 1, pick: 10, franchise: "Tino",       player: "Derrick Henry",        pos: "RB", keeper: false },
      { overall: 11, round: 1, pick: 11, franchise: "Sherlock",   player: "Jonathan Taylor",      pos: "RB", keeper: false },
      { overall: 12, round: 1, pick: 12, franchise: "Sorrentino", player: "Josh Allen",           pos: "QB", keeper: true  },
    ]
  },
];

// 2023 and 2024 full data from audited xlsx below
// 2023, 2024, 2025 full picks from audited xlsx

DRAFTS.push({
  year: 2023, rounds: 15, status: "complete",
  picks: [
    { overall: 1, round: 1, pick: 1, franchise: "Fritz", player: "Justin Jefferson(K)", pos: "WR", keeper: true },
    { overall: 2, round: 1, pick: 2, franchise: "Salsa Dick", player: "Christian McCaffrey(K)", pos: "RB", keeper: true },
    { overall: 3, round: 1, pick: 3, franchise: "Biceps Inc", player: "Bijan Robinson(K)", pos: "RB", keeper: true },
    { overall: 4, round: 1, pick: 4, franchise: "Boomer", player: "Austin Ekeler", pos: "RB", keeper: false },
    { overall: 5, round: 1, pick: 5, franchise: "Trust", player: "Tyreek Hill", pos: "WR", keeper: false },
    { overall: 6, round: 1, pick: 6, franchise: "Kam", player: "Cooper Kupp", pos: "WR", keeper: false },
    { overall: 7, round: 1, pick: 7, franchise: "Devany", player: "Travis Kelce", pos: "TE", keeper: false },
    { overall: 8, round: 1, pick: 8, franchise: "Magoo", player: "Stefon Diggs", pos: "WR", keeper: false },
    { overall: 9, round: 1, pick: 9, franchise: "Tino", player: "Derrick Henry", pos: "RB", keeper: false },
    { overall: 10, round: 1, pick: 10, franchise: "DDC", player: "Josh Jacobs", pos: "RB", keeper: false },
    { overall: 11, round: 1, pick: 11, franchise: "Sherlock", player: "Davante Adams", pos: "WR", keeper: false },
    { overall: 12, round: 1, pick: 12, franchise: "Vidz", player: "A.J. Brown", pos: "WR", keeper: false },
    { overall: 13, round: 2, pick: 1, franchise: "Fritz", player: "Nick Chubb(K)", pos: "RB", keeper: true },
    { overall: 14, round: 2, pick: 2, franchise: "Salsa Dick", player: "Mark Andrews", pos: "TE", keeper: false },
    { overall: 15, round: 2, pick: 3, franchise: "Biceps Inc", player: "Chris Olave", pos: "WR", keeper: false },
    { overall: 16, round: 2, pick: 4, franchise: "Boomer", player: "Jaylen Waddle", pos: "WR", keeper: false },
    { overall: 17, round: 2, pick: 5, franchise: "Trust", player: "Saquon Barkley(K)", pos: "RB", keeper: true },
    { overall: 18, round: 2, pick: 6, franchise: "Kam", player: "Najee Harris", pos: "RB", keeper: false },
    { overall: 19, round: 2, pick: 7, franchise: "Devany", player: "Jonathan Taylor", pos: "RB", keeper: false },
    { overall: 20, round: 2, pick: 8, franchise: "Magoo", player: "Patrick Mahomes", pos: "QB", keeper: false },
    { overall: 21, round: 2, pick: 9, franchise: "Tino", player: "Josh Allen", pos: "QB", keeper: false },
    { overall: 22, round: 2, pick: 10, franchise: "DDC", player: "Jahmyr Gibbs", pos: "RB", keeper: false },
    { overall: 23, round: 2, pick: 11, franchise: "Sherlock", player: "CeeDee Lamb", pos: "WR", keeper: false },
    { overall: 24, round: 2, pick: 12, franchise: "Vidz", player: "Amon-Ra St. Brown", pos: "WR", keeper: false },
    { overall: 25, round: 3, pick: 1, franchise: "Fritz", player: "Lamar Jackson", pos: "QB", keeper: false },
    { overall: 26, round: 3, pick: 2, franchise: "Salsa Dick", player: "Joe Mixon", pos: "RB", keeper: false },
    { overall: 27, round: 3, pick: 3, franchise: "Biceps Inc", player: "Breece Hall", pos: "RB", keeper: false },
    { overall: 28, round: 3, pick: 4, franchise: "Boomer", player: "Deebo Samuel", pos: "WR", keeper: false },
    { overall: 29, round: 3, pick: 5, franchise: "Trust", player: "Tee Higgins", pos: "WR", keeper: false },
    { overall: 30, round: 3, pick: 6, franchise: "Kam", player: "Javonte Williams", pos: "RB", keeper: false },
    { overall: 31, round: 3, pick: 7, franchise: "Devany", player: "Rhamondre Stevenson", pos: "RB", keeper: false },
    { overall: 32, round: 3, pick: 8, franchise: "Magoo", player: "Keenan Allen", pos: "WR", keeper: false },
    { overall: 33, round: 3, pick: 9, franchise: "Tino", player: "DeVonta Smith", pos: "WR", keeper: false },
    { overall: 34, round: 3, pick: 10, franchise: "DDC", player: "Amari Cooper", pos: "WR", keeper: false },
    { overall: 35, round: 3, pick: 11, franchise: "Sherlock", player: "Aaron Jones Sr.", pos: "RB", keeper: false },
    { overall: 36, round: 3, pick: 12, franchise: "Vidz", player: "Calvin Ridley", pos: "WR", keeper: false },
    { overall: 37, round: 4, pick: 1, franchise: "Fritz", player: "Jerry Jeudy", pos: "WR", keeper: false },
    { overall: 38, round: 4, pick: 2, franchise: "Salsa Dick", player: "DeAndre Hopkins", pos: "WR", keeper: false },
    { overall: 39, round: 4, pick: 3, franchise: "Biceps Inc", player: "DJ Moore", pos: "WR", keeper: false },
    { overall: 40, round: 4, pick: 4, franchise: "Boomer", player: "T.J. Hockenson", pos: "TE", keeper: false },
    { overall: 41, round: 4, pick: 5, franchise: "Trust", player: "Alvin Kamara", pos: "RB", keeper: false },
    { overall: 42, round: 4, pick: 6, franchise: "Kam", player: "Miles Sanders", pos: "RB", keeper: false },
    { overall: 43, round: 4, pick: 7, franchise: "Devany", player: "Ja\'Marr Chase(K)", pos: "WR", keeper: true },
    { overall: 44, round: 4, pick: 8, franchise: "Magoo", player: "James Conner", pos: "RB", keeper: false },
    { overall: 45, round: 4, pick: 9, franchise: "Tino", player: "Dameon Pierce", pos: "RB", keeper: false },
    { overall: 46, round: 4, pick: 10, franchise: "DDC", player: "Justin Fields", pos: "QB", keeper: false },
    { overall: 47, round: 4, pick: 11, franchise: "Sherlock", player: "DK Metcalf", pos: "WR", keeper: false },
    { overall: 48, round: 4, pick: 12, franchise: "Vidz", player: "J.K. Dobbins", pos: "RB", keeper: false },
    { overall: 49, round: 5, pick: 1, franchise: "Fritz", player: "Terry McLaurin", pos: "WR", keeper: false },
    { overall: 50, round: 5, pick: 2, franchise: "Salsa Dick", player: "Joe Burrow", pos: "QB", keeper: false },
    { overall: 51, round: 5, pick: 3, franchise: "Biceps Inc", player: "Isiah Pacheco", pos: "RB", keeper: false },
    { overall: 52, round: 5, pick: 4, franchise: "Boomer", player: "Justin Herbert", pos: "QB", keeper: false },
    { overall: 53, round: 5, pick: 5, franchise: "Trust", player: "George Kittle", pos: "TE", keeper: false },
    { overall: 54, round: 5, pick: 6, franchise: "Kam", player: "Drake London", pos: "WR", keeper: false },
    { overall: 55, round: 5, pick: 7, franchise: "Devany", player: "Mike Williams", pos: "WR", keeper: false },
    { overall: 56, round: 5, pick: 8, franchise: "Magoo", player: "Cam Akers", pos: "RB", keeper: false },
    { overall: 57, round: 5, pick: 9, franchise: "Tino", player: "Mike Evans", pos: "WR", keeper: false },
    { overall: 58, round: 5, pick: 10, franchise: "DDC", player: "Christian Watson", pos: "WR", keeper: false },
    { overall: 59, round: 5, pick: 11, franchise: "Sherlock", player: "Darren Waller", pos: "TE", keeper: false },
    { overall: 60, round: 5, pick: 12, franchise: "Vidz", player: "Jalen Hurts(K)", pos: "QB", keeper: true },
    { overall: 61, round: 6, pick: 1, franchise: "Fritz", player: "Evan Engram", pos: "TE", keeper: false },
    { overall: 62, round: 6, pick: 2, franchise: "Salsa Dick", player: "Diontae Johnson", pos: "WR", keeper: false },
    { overall: 63, round: 6, pick: 3, franchise: "Biceps Inc", player: "Michael Pittman Jr.", pos: "WR", keeper: false },
    { overall: 64, round: 6, pick: 4, franchise: "Boomer", player: "Khalil Herbert", pos: "RB", keeper: false },
    { overall: 65, round: 6, pick: 5, franchise: "Trust", player: "Chris Godwin Jr.", pos: "WR", keeper: false },
    { overall: 66, round: 6, pick: 6, franchise: "Kam", player: "Brian Robinson Jr.", pos: "RB", keeper: false },
    { overall: 67, round: 6, pick: 7, franchise: "Devany", player: "George Pickens", pos: "WR", keeper: false },
    { overall: 68, round: 6, pick: 8, franchise: "Magoo", player: "Kyle Pitts Sr.", pos: "TE", keeper: false },
    { overall: 69, round: 6, pick: 9, franchise: "Tino", player: "D\'Andre Swift", pos: "RB", keeper: false },
    { overall: 70, round: 6, pick: 10, franchise: "DDC", player: "Dallas Goedert", pos: "TE", keeper: false },
    { overall: 71, round: 6, pick: 11, franchise: "Sherlock", player: "Hollywood Brown", pos: "WR", keeper: false },
    { overall: 72, round: 6, pick: 12, franchise: "Vidz", player: "Dalvin Cook", pos: "RB", keeper: false },
    { overall: 73, round: 7, pick: 1, franchise: "Fritz", player: "David Montgomery", pos: "RB", keeper: false },
    { overall: 74, round: 7, pick: 2, franchise: "Salsa Dick", player: "Tony Pollard(K)", pos: "RB", keeper: true },
    { overall: 75, round: 7, pick: 3, franchise: "Biceps Inc", player: "Trevor Lawrence", pos: "QB", keeper: false },
    { overall: 76, round: 7, pick: 4, franchise: "Boomer", player: "Tyler Lockett", pos: "WR", keeper: false },
    { overall: 77, round: 7, pick: 5, franchise: "Trust", player: "Christian Kirk", pos: "WR", keeper: false },
    { overall: 78, round: 7, pick: 6, franchise: "Kam", player: "AJ Dillon", pos: "RB", keeper: false },
    { overall: 79, round: 7, pick: 7, franchise: "Devany", player: "Dak Prescott", pos: "QB", keeper: false },
    { overall: 80, round: 7, pick: 8, franchise: "Magoo", player: "Brandin Cooks", pos: "WR", keeper: false },
    { overall: 81, round: 7, pick: 9, franchise: "Tino", player: "Brandon Aiyuk(K)", pos: "WR", keeper: true },
    { overall: 82, round: 7, pick: 10, franchise: "DDC", player: "Jordan Addison", pos: "WR", keeper: false },
    { overall: 83, round: 7, pick: 11, franchise: "Sherlock", player: "Daniel Jones", pos: "QB", keeper: false },
    { overall: 84, round: 7, pick: 12, franchise: "Vidz", player: "Jahan Dotson", pos: "WR", keeper: false },
    { overall: 85, round: 8, pick: 1, franchise: "Fritz", player: "Samaje Perine", pos: "RB", keeper: false },
    { overall: 86, round: 8, pick: 2, franchise: "Salsa Dick", player: "Michael Thomas", pos: "WR", keeper: false },
    { overall: 87, round: 8, pick: 3, franchise: "Biceps Inc", player: "Jaxon Smith-Njigba", pos: "WR", keeper: false },
    { overall: 88, round: 8, pick: 4, franchise: "Boomer", player: "Quentin Johnston", pos: "WR", keeper: false },
    { overall: 89, round: 8, pick: 5, franchise: "Trust", player: "Gabe Davis", pos: "WR", keeper: false },
    { overall: 90, round: 8, pick: 6, franchise: "Kam", player: "Tua Tagovailoa", pos: "QB", keeper: false },
    { overall: 91, round: 8, pick: 7, franchise: "Devany", player: "Jamaal Williams", pos: "RB", keeper: false },
    { overall: 92, round: 8, pick: 8, franchise: "Magoo", player: "Courtland Sutton", pos: "WR", keeper: false },
    { overall: 93, round: 8, pick: 9, franchise: "Tino", player: "Antonio Gibson", pos: "RB", keeper: false },
    { overall: 94, round: 8, pick: 10, franchise: "DDC", player: "Travis Etienne Jr.(K)", pos: "RB", keeper: true },
    { overall: 95, round: 8, pick: 11, franchise: "Sherlock", player: "Kenneth Walker III(K)", pos: "RB", keeper: true },
    { overall: 96, round: 8, pick: 12, franchise: "Vidz", player: "Zach Charbonnet", pos: "RB", keeper: false },
    { overall: 97, round: 9, pick: 1, franchise: "Fritz", player: "Jerick McKinnon", pos: "RB", keeper: false },
    { overall: 98, round: 9, pick: 2, franchise: "Salsa Dick", player: "Rashaad Penny", pos: "RB", keeper: false },
    { overall: 99, round: 9, pick: 3, franchise: "Biceps Inc", player: "Ezekiel Elliott", pos: "RB", keeper: false },
    { overall: 100, round: 9, pick: 4, franchise: "Boomer", player: "Jeff Wilson Jr.", pos: "RB", keeper: false },
    { overall: 101, round: 9, pick: 5, franchise: "Trust", player: "Raheem Mostert", pos: "RB", keeper: false },
    { overall: 102, round: 9, pick: 6, franchise: "Kam", player: "Romeo Doubs", pos: "WR", keeper: false },
    { overall: 103, round: 9, pick: 7, franchise: "Devany", player: "Kadarius Toney", pos: "WR", keeper: false },
    { overall: 104, round: 9, pick: 8, franchise: "Magoo", player: "Pat Freiermuth", pos: "TE", keeper: false },
    { overall: 105, round: 9, pick: 9, franchise: "Tino", player: "Damien Harris", pos: "RB", keeper: false },
    { overall: 106, round: 9, pick: 10, franchise: "DDC", player: "Elijah Mitchell", pos: "RB", keeper: false },
    { overall: 107, round: 9, pick: 11, franchise: "Sherlock", player: "Skyy Moore", pos: "WR", keeper: false },
    { overall: 108, round: 9, pick: 12, franchise: "Vidz", player: "De\'Von Achane", pos: "RB", keeper: false },
    { overall: 109, round: 10, pick: 1, franchise: "Fritz", player: "Dalton Schultz", pos: "TE", keeper: false },
    { overall: 110, round: 10, pick: 2, franchise: "Salsa Dick", player: "Roschon Johnson", pos: "RB", keeper: false },
    { overall: 111, round: 10, pick: 3, franchise: "Biceps Inc", player: "Garrett Wilson(K)", pos: "WR", keeper: true },
    { overall: 112, round: 10, pick: 4, franchise: "Boomer", player: "James Cook III(K)", pos: "RB", keeper: true },
    { overall: 113, round: 10, pick: 5, franchise: "Trust", player: "Devin Singletary", pos: "RB", keeper: false },
    { overall: 114, round: 10, pick: 6, franchise: "Kam", player: "Rachaad White(K)", pos: "RB", keeper: true },
    { overall: 115, round: 10, pick: 7, franchise: "Devany", player: "Tyler Allgeier", pos: "RB", keeper: false },
    { overall: 116, round: 10, pick: 8, franchise: "Magoo", player: "Alexander Mattison(K)", pos: "RB", keeper: true },
    { overall: 117, round: 10, pick: 9, franchise: "Tino", player: "Allen Lazard", pos: "WR", keeper: false },
    { overall: 118, round: 10, pick: 10, franchise: "DDC", player: "Rashod Bateman", pos: "WR", keeper: false },
    { overall: 119, round: 10, pick: 11, franchise: "Sherlock", player: "Tank Bigsby", pos: "RB", keeper: false },
    { overall: 120, round: 10, pick: 12, franchise: "Vidz", player: "Odell Beckham Jr.", pos: "WR", keeper: false },
    { overall: 121, round: 11, pick: 1, franchise: "Fritz", player: "Justin Tucker", pos: "PK", keeper: false },
    { overall: 122, round: 11, pick: 2, franchise: "Salsa Dick", player: "SF DEF", pos: "DEF", keeper: false },
    { overall: 123, round: 11, pick: 3, franchise: "Biceps Inc", player: "Jameson Williams", pos: "WR", keeper: false },
    { overall: 124, round: 11, pick: 4, franchise: "Boomer", player: "Michael Gallup", pos: "WR", keeper: false },
    { overall: 125, round: 11, pick: 5, franchise: "Trust", player: "Deshaun Watson", pos: "QB", keeper: false },
    { overall: 126, round: 11, pick: 6, franchise: "Kam", player: "David Njoku", pos: "TE", keeper: false },
    { overall: 127, round: 11, pick: 7, franchise: "Devany", player: "Treylon Burks", pos: "WR", keeper: false },
    { overall: 128, round: 11, pick: 8, franchise: "Magoo", player: "JuJu Smith-Schuster", pos: "WR", keeper: false },
    { overall: 129, round: 11, pick: 9, franchise: "Tino", player: "DeWayne McBride", pos: "RB", keeper: false },
    { overall: 130, round: 11, pick: 10, franchise: "DDC", player: "Kenneth Gainwell", pos: "RB", keeper: false },
    { overall: 131, round: 11, pick: 11, franchise: "Sherlock", player: "Adam Thielen", pos: "WR", keeper: false },
    { overall: 132, round: 11, pick: 12, franchise: "Vidz", player: "Jaylen Warren", pos: "RB", keeper: false },
    { overall: 133, round: 12, pick: 1, franchise: "Fritz", player: "BAL DEF", pos: "DEF", keeper: false },
    { overall: 134, round: 12, pick: 2, franchise: "Salsa Dick", player: "Gus Edwards", pos: "RB", keeper: false },
    { overall: 135, round: 12, pick: 3, franchise: "Biceps Inc", player: "Zamir White", pos: "RB", keeper: false },
    { overall: 136, round: 12, pick: 4, franchise: "Boomer", player: "NO DEF", pos: "DEF", keeper: false },
    { overall: 137, round: 12, pick: 5, franchise: "Trust", player: "Kendre Miller", pos: "RB", keeper: false },
    { overall: 138, round: 12, pick: 6, franchise: "Kam", player: "BUF DEF", pos: "DEF", keeper: false },
    { overall: 139, round: 12, pick: 7, franchise: "Devany", player: "Tyler Bass", pos: "PK", keeper: false },
    { overall: 140, round: 12, pick: 8, franchise: "Magoo", player: "Elijah Moore", pos: "WR", keeper: false },
    { overall: 141, round: 12, pick: 9, franchise: "Tino", player: "Aaron Rodgers", pos: "QB", keeper: false },
    { overall: 142, round: 12, pick: 10, franchise: "DDC", player: "Nico Collins", pos: "WR", keeper: false },
    { overall: 143, round: 12, pick: 11, franchise: "Sherlock", player: "Tyjae Spears", pos: "RB", keeper: false },
    { overall: 144, round: 12, pick: 12, franchise: "Vidz", player: "PHI DEF", pos: "DEF", keeper: false },
    { overall: 145, round: 13, pick: 1, franchise: "Fritz", player: "Chuba Hubbard", pos: "RB", keeper: false },
    { overall: 146, round: 13, pick: 2, franchise: "Salsa Dick", player: "Zay Flowers", pos: "WR", keeper: false },
    { overall: 147, round: 13, pick: 3, franchise: "Biceps Inc", player: "Dalton Kincaid", pos: "TE", keeper: false },
    { overall: 148, round: 13, pick: 4, franchise: "Boomer", player: "Daniel Carlson", pos: "PK", keeper: false },
    { overall: 149, round: 13, pick: 5, franchise: "Trust", player: "Jerome Ford", pos: "RB", keeper: false },
    { overall: 150, round: 13, pick: 6, franchise: "Kam", player: "Evan McPherson", pos: "PK", keeper: false },
    { overall: 151, round: 13, pick: 7, franchise: "Devany", player: "DAL DEF", pos: "DEF", keeper: false },
    { overall: 152, round: 13, pick: 8, franchise: "Magoo", player: "NYJ DEF", pos: "DEF", keeper: false },
    { overall: 153, round: 13, pick: 9, franchise: "Tino", player: "NE DEF", pos: "DEF", keeper: false },
    { overall: 154, round: 13, pick: 10, franchise: "DDC", player: "PIT DEF", pos: "DEF", keeper: false },
    { overall: 155, round: 13, pick: 11, franchise: "Sherlock", player: "Gerald Everett", pos: "TE", keeper: false },
    { overall: 156, round: 13, pick: 12, franchise: "Vidz", player: "DJ Chark", pos: "WR", keeper: false },
    { overall: 157, round: 14, pick: 1, franchise: "Fritz", player: "Anthony Richardson Sr.", pos: "QB", keeper: false },
    { overall: 158, round: 14, pick: 2, franchise: "Salsa Dick", player: "Darnell Mooney", pos: "WR", keeper: false },
    { overall: 159, round: 14, pick: 3, franchise: "Biceps Inc", player: "MIA DEF", pos: "DEF", keeper: false },
    { overall: 160, round: 14, pick: 4, franchise: "Boomer", player: "Kirk Cousins", pos: "QB", keeper: false },
    { overall: 161, round: 14, pick: 5, franchise: "Trust", player: "KC DEF", pos: "DEF", keeper: false },
    { overall: 162, round: 14, pick: 6, franchise: "Kam", player: "Terrace Marshall Jr.", pos: "WR", keeper: false },
    { overall: 163, round: 14, pick: 7, franchise: "Devany", player: "Jakobi Meyers", pos: "WR", keeper: false },
    { overall: 164, round: 14, pick: 8, franchise: "Magoo", player: "Leonard Fournette", pos: "RB", keeper: false },
    { overall: 165, round: 14, pick: 9, franchise: "Tino", player: "Chig Okonkwo", pos: "TE", keeper: false },
    { overall: 166, round: 14, pick: 10, franchise: "DDC", player: "Harrison Butker", pos: "PK", keeper: false },
    { overall: 167, round: 14, pick: 11, franchise: "Sherlock", player: "GB DEF", pos: "DEF", keeper: false },
    { overall: 168, round: 14, pick: 12, franchise: "Vidz", player: "Tyler Conklin", pos: "TE", keeper: false },
    { overall: 169, round: 15, pick: 1, franchise: "Fritz", player: "Tyler Higbee", pos: "TE", keeper: false },
    { overall: 170, round: 15, pick: 2, franchise: "Salsa Dick", player: "Graham Gano", pos: "PK", keeper: false },
    { overall: 171, round: 15, pick: 3, franchise: "Biceps Inc", player: "Younghoe Koo", pos: "PK", keeper: false },
    { overall: 172, round: 15, pick: 4, franchise: "Boomer", player: "Cordarrelle Patterson", pos: "RB", keeper: false },
    { overall: 173, round: 15, pick: 5, franchise: "Trust", player: "Kareem Hunt", pos: "RB", keeper: false },
    { overall: 174, round: 15, pick: 6, franchise: "Kam", player: "K.J. Osborn", pos: "WR", keeper: false },
    { overall: 175, round: 15, pick: 7, franchise: "Devany", player: "Clyde Edwards-Helaire", pos: "RB", keeper: false },
    { overall: 176, round: 15, pick: 8, franchise: "Magoo", player: "Jalin Hyatt", pos: "WR", keeper: false },
    { overall: 177, round: 15, pick: 9, franchise: "Tino", player: "Greg Zuerlein", pos: "PK", keeper: false },
    { overall: 178, round: 15, pick: 10, franchise: "DDC", player: "John Metchie III", pos: "WR", keeper: false },
    { overall: 179, round: 15, pick: 11, franchise: "Sherlock", player: "Geno Smith", pos: "QB", keeper: false },
    { overall: 180, round: 15, pick: 12, franchise: "Vidz", player: "Michael Wilson", pos: "WR", keeper: false },
  ]
});

DRAFTS.push({
  year: 2024, rounds: 15, status: "complete",
  picks: [
    { overall: 1, round: 1, pick: 1, franchise: "Sherlock", player: "CeeDee Lamb", pos: "WR", keeper: false },
    { overall: 2, round: 1, pick: 2, franchise: "Devany", player: "Bijan Robinson", pos: "RB", keeper: false },
    { overall: 3, round: 1, pick: 3, franchise: "Tino", player: "Justin Jefferson", pos: "WR", keeper: false },
    { overall: 4, round: 1, pick: 4, franchise: "Magoo", player: "Amon-Ra St. Brown", pos: "WR", keeper: false },
    { overall: 5, round: 1, pick: 5, franchise: "Biceps Inc", player: "Ja\'Marr Chase", pos: "WR", keeper: false },
    { overall: 6, round: 1, pick: 6, franchise: "Vidz", player: "A.J. Brown", pos: "WR", keeper: false },
    { overall: 7, round: 1, pick: 7, franchise: "Salsa Dick", player: "Christian McCaffrey(K)", pos: "RB", keeper: true },
    { overall: 8, round: 1, pick: 8, franchise: "Kam", player: "Jonathan Taylor", pos: "RB", keeper: false },
    { overall: 9, round: 1, pick: 9, franchise: "Trust", player: "Tyreek Hill(K)", pos: "WR", keeper: true },
    { overall: 10, round: 1, pick: 10, franchise: "Boomer", player: "Jahmyr Gibbs", pos: "RB", keeper: false },
    { overall: 11, round: 1, pick: 11, franchise: "DDC", player: "Derrick Henry", pos: "RB", keeper: false },
    { overall: 12, round: 1, pick: 12, franchise: "Fritz", player: "Saquon Barkley", pos: "RB", keeper: false },
    { overall: 13, round: 2, pick: 1, franchise: "Sherlock", player: "Drake London", pos: "WR", keeper: false },
    { overall: 14, round: 2, pick: 2, franchise: "Devany", player: "Brandon Aiyuk", pos: "WR", keeper: false },
    { overall: 15, round: 2, pick: 3, franchise: "Tino", player: "Josh Allen(K)", pos: "QB", keeper: true },
    { overall: 16, round: 2, pick: 4, franchise: "Magoo", player: "De\'Von Achane", pos: "RB", keeper: false },
    { overall: 17, round: 2, pick: 5, franchise: "Biceps Inc", player: "Marvin Harrison Jr.", pos: "WR", keeper: false },
    { overall: 18, round: 2, pick: 6, franchise: "Vidz", player: "Cooper Kupp", pos: "WR", keeper: false },
    { overall: 19, round: 2, pick: 7, franchise: "Salsa Dick", player: "Deebo Samuel", pos: "WR", keeper: false },
    { overall: 20, round: 2, pick: 8, franchise: "Kam", player: "Jalen Hurts", pos: "QB", keeper: false },
    { overall: 21, round: 2, pick: 9, franchise: "Trust", player: "Isiah Pacheco", pos: "RB", keeper: false },
    { overall: 22, round: 2, pick: 10, franchise: "Boomer", player: "Chris Olave", pos: "WR", keeper: false },
    { overall: 23, round: 2, pick: 11, franchise: "DDC", player: "Travis Etienne Jr.", pos: "RB", keeper: false },
    { overall: 24, round: 2, pick: 12, franchise: "Fritz", player: "Davante Adams", pos: "WR", keeper: false },
    { overall: 25, round: 3, pick: 1, franchise: "Sherlock", player: "Breece Hall(K)", pos: "RB", keeper: true },
    { overall: 26, round: 3, pick: 2, franchise: "Devany", player: "DK Metcalf", pos: "WR", keeper: false },
    { overall: 27, round: 3, pick: 3, franchise: "Tino", player: "Jaylen Waddle", pos: "WR", keeper: false },
    { overall: 28, round: 3, pick: 4, franchise: "Magoo", player: "Patrick Mahomes", pos: "QB", keeper: false },
    { overall: 29, round: 3, pick: 5, franchise: "Biceps Inc", player: "Kenneth Walker III", pos: "RB", keeper: false },
    { overall: 30, round: 3, pick: 6, franchise: "Vidz", player: "Josh Jacobs", pos: "RB", keeper: false },
    { overall: 31, round: 3, pick: 7, franchise: "Salsa Dick", player: "Sam LaPorta", pos: "TE", keeper: false },
    { overall: 32, round: 3, pick: 8, franchise: "Kam", player: "Rachaad White", pos: "RB", keeper: false },
    { overall: 33, round: 3, pick: 9, franchise: "Trust", player: "Travis Kelce", pos: "TE", keeper: false },
    { overall: 34, round: 3, pick: 10, franchise: "Boomer", player: "Mike Evans", pos: "WR", keeper: false },
    { overall: 35, round: 3, pick: 11, franchise: "DDC", player: "Joe Mixon", pos: "RB", keeper: false },
    { overall: 36, round: 3, pick: 12, franchise: "Fritz", player: "Alvin Kamara", pos: "RB", keeper: false },
    { overall: 37, round: 4, pick: 1, franchise: "Sherlock", player: "Jordan Love", pos: "QB", keeper: false },
    { overall: 38, round: 4, pick: 2, franchise: "Devany", player: "Mark Andrews", pos: "TE", keeper: false },
    { overall: 39, round: 4, pick: 3, franchise: "Tino", player: "David Montgomery", pos: "RB", keeper: false },
    { overall: 40, round: 4, pick: 4, franchise: "Magoo", player: "Tee Higgins", pos: "WR", keeper: false },
    { overall: 41, round: 4, pick: 5, franchise: "Biceps Inc", player: "Aaron Jones Sr.", pos: "RB", keeper: false },
    { overall: 42, round: 4, pick: 6, franchise: "Vidz", player: "Kyler Murray", pos: "QB", keeper: false },
    { overall: 43, round: 4, pick: 7, franchise: "Salsa Dick", player: "DJ Moore", pos: "WR", keeper: false },
    { overall: 44, round: 4, pick: 8, franchise: "Kam", player: "Malik Nabers", pos: "WR", keeper: false },
    { overall: 45, round: 4, pick: 9, franchise: "Trust", player: "Michael Pittman Jr.", pos: "WR", keeper: false },
    { overall: 46, round: 4, pick: 10, franchise: "Boomer", player: "Stefon Diggs", pos: "WR", keeper: false },
    { overall: 47, round: 4, pick: 11, franchise: "DDC", player: "DeVonta Smith", pos: "WR", keeper: false },
    { overall: 48, round: 4, pick: 12, franchise: "Fritz", player: "Lamar Jackson", pos: "QB", keeper: false },
    { overall: 49, round: 5, pick: 1, franchise: "Sherlock", player: "Zay Flowers", pos: "WR", keeper: false },
    { overall: 50, round: 5, pick: 2, franchise: "Devany", player: "Tank Dell", pos: "WR", keeper: false },
    { overall: 51, round: 5, pick: 3, franchise: "Tino", player: "Amari Cooper", pos: "WR", keeper: false },
    { overall: 52, round: 5, pick: 4, franchise: "Magoo", player: "Terry McLaurin", pos: "WR", keeper: false },
    { overall: 53, round: 5, pick: 5, franchise: "Biceps Inc", player: "D\'Andre Swift", pos: "RB", keeper: false },
    { overall: 54, round: 5, pick: 6, franchise: "Vidz", player: "Najee Harris", pos: "RB", keeper: false },
    { overall: 55, round: 5, pick: 7, franchise: "Salsa Dick", player: "Anthony Richardson Sr.", pos: "QB", keeper: false },
    { overall: 56, round: 5, pick: 8, franchise: "Kam", player: "James Conner", pos: "RB", keeper: false },
    { overall: 57, round: 5, pick: 9, franchise: "Trust", player: "Rhamondre Stevenson", pos: "RB", keeper: false },
    { overall: 58, round: 5, pick: 10, franchise: "Boomer", player: "Joe Burrow", pos: "QB", keeper: false },
    { overall: 59, round: 5, pick: 11, franchise: "DDC", player: "George Pickens", pos: "WR", keeper: false },
    { overall: 60, round: 5, pick: 12, franchise: "Fritz", player: "Christian Kirk", pos: "WR", keeper: false },
    { overall: 61, round: 6, pick: 1, franchise: "Sherlock", player: "George Kittle", pos: "TE", keeper: false },
    { overall: 62, round: 6, pick: 2, franchise: "Devany", player: "Zack Moss", pos: "RB", keeper: false },
    { overall: 63, round: 6, pick: 3, franchise: "Tino", player: "Brian Robinson Jr.", pos: "RB", keeper: false },
    { overall: 64, round: 6, pick: 4, franchise: "Magoo", player: "Javonte Williams", pos: "RB", keeper: false },
    { overall: 65, round: 6, pick: 5, franchise: "Biceps Inc", player: "Kyle Pitts Sr.", pos: "TE", keeper: false },
    { overall: 66, round: 6, pick: 6, franchise: "Vidz", player: "Diontae Johnson", pos: "WR", keeper: false },
    { overall: 67, round: 6, pick: 7, franchise: "Salsa Dick", player: "Raheem Mostert", pos: "RB", keeper: false },
    { overall: 68, round: 6, pick: 8, franchise: "Kam", player: "Calvin Ridley", pos: "WR", keeper: false },
    { overall: 69, round: 6, pick: 9, franchise: "Trust", player: "Tony Pollard", pos: "RB", keeper: false },
    { overall: 70, round: 6, pick: 10, franchise: "Boomer", player: "Trey McBride", pos: "TE", keeper: false },
    { overall: 71, round: 6, pick: 11, franchise: "DDC", player: "Dalton Kincaid", pos: "TE", keeper: false },
    { overall: 72, round: 6, pick: 12, franchise: "Fritz", player: "Zamir White", pos: "RB", keeper: false },
    { overall: 73, round: 7, pick: 1, franchise: "Sherlock", player: "Devin Singletary", pos: "RB", keeper: false },
    { overall: 74, round: 7, pick: 2, franchise: "Devany", player: "Jaylen Warren", pos: "RB", keeper: false },
    { overall: 75, round: 7, pick: 3, franchise: "Tino", player: "Chase Brown", pos: "RB", keeper: false },
    { overall: 76, round: 7, pick: 4, franchise: "Magoo", player: "Keenan Allen", pos: "WR", keeper: false },
    { overall: 77, round: 7, pick: 5, franchise: "Biceps Inc", player: "Nick Chubb", pos: "RB", keeper: false },
    { overall: 78, round: 7, pick: 6, franchise: "Vidz", player: "Rome Odunze", pos: "WR", keeper: false },
    { overall: 79, round: 7, pick: 7, franchise: "Salsa Dick", player: "Jonathon Brooks", pos: "RB", keeper: false },
    { overall: 80, round: 7, pick: 8, franchise: "Kam", player: "Evan Engram", pos: "TE", keeper: false },
    { overall: 81, round: 7, pick: 9, franchise: "Trust", player: "Chris Godwin Jr.", pos: "WR", keeper: false },
    { overall: 82, round: 7, pick: 10, franchise: "Boomer", player: "Austin Ekeler", pos: "RB", keeper: false },
    { overall: 83, round: 7, pick: 11, franchise: "DDC", player: "Tyjae Spears", pos: "RB", keeper: false },
    { overall: 84, round: 7, pick: 12, franchise: "Fritz", player: "Jayden Reed", pos: "WR", keeper: false },
    { overall: 85, round: 8, pick: 1, franchise: "Sherlock", player: "Keon Coleman", pos: "WR", keeper: false },
    { overall: 86, round: 8, pick: 2, franchise: "Devany", player: "Xavier Worthy", pos: "WR", keeper: false },
    { overall: 87, round: 8, pick: 3, franchise: "Tino", player: "Tua Tagovailoa", pos: "QB", keeper: false },
    { overall: 88, round: 8, pick: 4, franchise: "Magoo", player: "Ezekiel Elliott", pos: "RB", keeper: false },
    { overall: 89, round: 8, pick: 5, franchise: "Biceps Inc", player: "Garrett Wilson(K)", pos: "WR", keeper: true },
    { overall: 90, round: 8, pick: 6, franchise: "Vidz", player: "Dak Prescott", pos: "QB", keeper: false },
    { overall: 91, round: 8, pick: 7, franchise: "Salsa Dick", player: "Jerome Ford", pos: "RB", keeper: false },
    { overall: 92, round: 8, pick: 8, franchise: "Kam", player: "Brock Bowers", pos: "TE", keeper: false },
    { overall: 93, round: 8, pick: 9, franchise: "Trust", player: "Christian Watson", pos: "WR", keeper: false },
    { overall: 94, round: 8, pick: 10, franchise: "Boomer", player: "James Cook III(K)", pos: "RB", keeper: true },
    { overall: 95, round: 8, pick: 11, franchise: "DDC", player: "Jayden Daniels", pos: "QB", keeper: false },
    { overall: 96, round: 8, pick: 12, franchise: "Fritz", player: "David Njoku", pos: "TE", keeper: false },
    { overall: 97, round: 9, pick: 1, franchise: "Sherlock", player: "J.K. Dobbins", pos: "RB", keeper: false },
    { overall: 98, round: 9, pick: 2, franchise: "Devany", player: "Jordan Addison", pos: "WR", keeper: false },
    { overall: 99, round: 9, pick: 3, franchise: "Tino", player: "Courtland Sutton", pos: "WR", keeper: false },
    { overall: 100, round: 9, pick: 4, franchise: "Magoo", player: "Ladd McConkey", pos: "WR", keeper: false },
    { overall: 101, round: 9, pick: 5, franchise: "Biceps Inc", player: "Jameson Williams", pos: "WR", keeper: false },
    { overall: 102, round: 9, pick: 6, franchise: "Vidz", player: "BAL DEF", pos: "DEF", keeper: false },
    { overall: 103, round: 9, pick: 7, franchise: "Salsa Dick", player: "Hollywood Brown", pos: "WR", keeper: false },
    { overall: 104, round: 9, pick: 8, franchise: "Kam", player: "Gus Edwards", pos: "RB", keeper: false },
    { overall: 105, round: 9, pick: 9, franchise: "Trust", player: "Rico Dowdle", pos: "RB", keeper: false },
    { overall: 106, round: 9, pick: 10, franchise: "Boomer", player: "Jaxon Smith-Njigba", pos: "WR", keeper: false },
    { overall: 107, round: 9, pick: 11, franchise: "DDC", player: "Trey Benson", pos: "RB", keeper: false },
    { overall: 108, round: 9, pick: 12, franchise: "Fritz", player: "DeAndre Hopkins", pos: "WR", keeper: false },
    { overall: 109, round: 10, pick: 1, franchise: "Sherlock", player: "Chuba Hubbard", pos: "RB", keeper: false },
    { overall: 110, round: 10, pick: 2, franchise: "Devany", player: "C.J. Stroud(K)", pos: "QB", keeper: true },
    { overall: 111, round: 10, pick: 3, franchise: "Tino", player: "Dallas Goedert", pos: "TE", keeper: false },
    { overall: 112, round: 10, pick: 4, franchise: "Magoo", player: "Jake Ferguson(K)", pos: "TE", keeper: true },
    { overall: 113, round: 10, pick: 5, franchise: "Biceps Inc", player: "Zach Charbonnet", pos: "RB", keeper: false },
    { overall: 114, round: 10, pick: 6, franchise: "Vidz", player: "Kyren Williams(K)", pos: "RB", keeper: true },
    { overall: 115, round: 10, pick: 7, franchise: "Salsa Dick", player: "Jaylen Wright", pos: "RB", keeper: false },
    { overall: 116, round: 10, pick: 8, franchise: "Kam", player: "Puka Nacua(K)", pos: "WR", keeper: true },
    { overall: 117, round: 10, pick: 9, franchise: "Trust", player: "Caleb Williams", pos: "QB", keeper: false },
    { overall: 118, round: 10, pick: 10, franchise: "Boomer", player: "Blake Corum", pos: "RB", keeper: false },
    { overall: 119, round: 10, pick: 11, franchise: "DDC", player: "Nico Collins(K)", pos: "WR", keeper: true },
    { overall: 120, round: 10, pick: 12, franchise: "Fritz", player: "Rashee Rice(K)", pos: "WR", keeper: true },
    { overall: 121, round: 11, pick: 1, franchise: "Sherlock", player: "Dalton Schultz", pos: "TE", keeper: false },
    { overall: 122, round: 11, pick: 2, franchise: "Devany", player: "Mike Williams", pos: "WR", keeper: false },
    { overall: 123, round: 11, pick: 3, franchise: "Tino", player: "Curtis Samuel", pos: "WR", keeper: false },
    { overall: 124, round: 11, pick: 4, franchise: "Magoo", player: "Tyler Allgeier", pos: "RB", keeper: false },
    { overall: 125, round: 11, pick: 5, franchise: "Biceps Inc", player: "Romeo Doubs", pos: "WR", keeper: false },
    { overall: 126, round: 11, pick: 6, franchise: "Vidz", player: "Brian Thomas Jr.", pos: "WR", keeper: false },
    { overall: 127, round: 11, pick: 7, franchise: "Salsa Dick", player: "NYJ DEF", pos: "DEF", keeper: false },
    { overall: 128, round: 11, pick: 8, franchise: "Kam", player: "Khalil Shakir", pos: "WR", keeper: false },
    { overall: 129, round: 11, pick: 9, franchise: "Trust", player: "Jerry Jeudy", pos: "WR", keeper: false },
    { overall: 130, round: 11, pick: 10, franchise: "Boomer", player: "CLE DEF", pos: "DEF", keeper: false },
    { overall: 131, round: 11, pick: 11, franchise: "DDC", player: "Justin Herbert", pos: "QB", keeper: false },
    { overall: 132, round: 11, pick: 12, franchise: "Fritz", player: "Ty Chandler", pos: "RB", keeper: false },
    { overall: 133, round: 12, pick: 1, franchise: "Sherlock", player: "Darnell Mooney", pos: "WR", keeper: false },
    { overall: 134, round: 12, pick: 2, franchise: "Devany", player: "Harrison Butker", pos: "PK", keeper: false },
    { overall: 135, round: 12, pick: 3, franchise: "Tino", player: "DAL DEF", pos: "DEF", keeper: false },
    { overall: 136, round: 12, pick: 4, franchise: "Magoo", player: "Ray Davis", pos: "RB", keeper: false },
    { overall: 137, round: 12, pick: 5, franchise: "Biceps Inc", player: "Jared Goff", pos: "QB", keeper: false },
    { overall: 138, round: 12, pick: 6, franchise: "Vidz", player: "Khalil Herbert", pos: "RB", keeper: false },
    { overall: 139, round: 12, pick: 7, franchise: "Salsa Dick", player: "Justin Tucker", pos: "PK", keeper: false },
    { overall: 140, round: 12, pick: 8, franchise: "Kam", player: "Jaleel McLaughlin", pos: "RB", keeper: false },
    { overall: 141, round: 12, pick: 9, franchise: "Trust", player: "Tyrone Tracy Jr.", pos: "RB", keeper: false },
    { overall: 142, round: 12, pick: 10, franchise: "Boomer", player: "MarShawn Lloyd", pos: "RB", keeper: false },
    { overall: 143, round: 12, pick: 11, franchise: "DDC", player: "KC DEF", pos: "DEF", keeper: false },
    { overall: 144, round: 12, pick: 12, franchise: "Fritz", player: "SF DEF", pos: "DEF", keeper: false },
    { overall: 145, round: 13, pick: 1, franchise: "Sherlock", player: "Bucky Irving", pos: "RB", keeper: false },
    { overall: 146, round: 13, pick: 2, franchise: "Devany", player: "Antonio Gibson", pos: "RB", keeper: false },
    { overall: 147, round: 13, pick: 3, franchise: "Tino", player: "Brandin Cooks", pos: "WR", keeper: false },
    { overall: 148, round: 13, pick: 4, franchise: "Magoo", player: "Tyler Lockett", pos: "WR", keeper: false },
    { overall: 149, round: 13, pick: 5, franchise: "Biceps Inc", player: "Aaron Rodgers", pos: "QB", keeper: false },
    { overall: 150, round: 13, pick: 6, franchise: "Vidz", player: "Noah Fant", pos: "TE", keeper: false },
    { overall: 151, round: 13, pick: 7, franchise: "Salsa Dick", player: "Jakobi Meyers", pos: "WR", keeper: false },
    { overall: 152, round: 13, pick: 8, franchise: "Kam", player: "PIT DEF", pos: "DEF", keeper: false },
    { overall: 153, round: 13, pick: 9, franchise: "Trust", player: "Trevor Lawrence", pos: "QB", keeper: false },
    { overall: 154, round: 13, pick: 10, franchise: "Boomer", player: "Greg Zuerlein", pos: "PK", keeper: false },
    { overall: 155, round: 13, pick: 11, franchise: "DDC", player: "Brock Purdy", pos: "QB", keeper: false },
    { overall: 156, round: 13, pick: 12, franchise: "Fritz", player: "Kendre Miller", pos: "RB", keeper: false },
    { overall: 157, round: 14, pick: 1, franchise: "Sherlock", player: "Ka\'imi Fairbairn", pos: "PK", keeper: false },
    { overall: 158, round: 14, pick: 2, franchise: "Devany", player: "Jahan Dotson", pos: "WR", keeper: false },
    { overall: 159, round: 14, pick: 3, franchise: "Tino", player: "Jake Moody", pos: "PK", keeper: false },
    { overall: 160, round: 14, pick: 4, franchise: "Magoo", player: "Elijah Mitchell", pos: "RB", keeper: false },
    { overall: 161, round: 14, pick: 5, franchise: "Biceps Inc", player: "Younghoe Koo", pos: "PK", keeper: false },
    { overall: 162, round: 14, pick: 6, franchise: "Vidz", player: "Jason Sanders", pos: "PK", keeper: false },
    { overall: 163, round: 14, pick: 7, franchise: "Salsa Dick", player: "T.J. Hockenson", pos: "TE", keeper: false },
    { overall: 164, round: 14, pick: 8, franchise: "Kam", player: "Jake Elliott", pos: "PK", keeper: false },
    { overall: 165, round: 14, pick: 9, franchise: "Trust", player: "MIA DEF", pos: "DEF", keeper: false },
    { overall: 166, round: 14, pick: 10, franchise: "Boomer", player: "Kirk Cousins", pos: "QB", keeper: false },
    { overall: 167, round: 14, pick: 11, franchise: "DDC", player: "Dontayvion Wicks", pos: "WR", keeper: false },
    { overall: 168, round: 14, pick: 12, franchise: "Fritz", player: "Brandon Aubrey", pos: "PK", keeper: false },
    { overall: 169, round: 15, pick: 1, franchise: "Sherlock", player: "BUF DEF", pos: "DEF", keeper: false },
    { overall: 170, round: 15, pick: 2, franchise: "Devany", player: "Dameon Pierce", pos: "RB", keeper: false },
    { overall: 171, round: 15, pick: 3, franchise: "Tino", player: "Braelon Allen", pos: "RB", keeper: false },
    { overall: 172, round: 15, pick: 4, franchise: "Magoo", player: "Tyler Bass", pos: "PK", keeper: false },
    { overall: 173, round: 15, pick: 5, franchise: "Biceps Inc", player: "PHI DEF", pos: "DEF", keeper: false },
    { overall: 174, round: 15, pick: 6, franchise: "Vidz", player: "Ben Sinnott", pos: "TE", keeper: false },
    { overall: 175, round: 15, pick: 7, franchise: "Salsa Dick", player: "Luke McCaffrey", pos: "WR", keeper: false },
    { overall: 176, round: 15, pick: 8, franchise: "Kam", player: "Kimani Vidal", pos: "RB", keeper: false },
    { overall: 177, round: 15, pick: 9, franchise: "Trust", player: "Evan McPherson", pos: "PK", keeper: false },
    { overall: 178, round: 15, pick: 10, franchise: "Boomer", player: "Rashid Shaheed", pos: "WR", keeper: false },
    { overall: 179, round: 15, pick: 11, franchise: "DDC", player: "Cairo Santos", pos: "PK", keeper: false },
    { overall: 180, round: 15, pick: 12, franchise: "Fritz", player: "Joshua Palmer", pos: "WR", keeper: false },
  ]
});

DRAFTS.push({
  year: 2025, rounds: 15, status: "complete",
  picks: [
    { overall: 1, round: 1, pick: 1, franchise: "Tino", player: "Justin Jefferson(K)", pos: "WR", keeper: true },
    { overall: 2, round: 1, pick: 2, franchise: "Salsa Dick", player: "Ja\'Marr Chase", pos: "WR", keeper: false },
    { overall: 3, round: 1, pick: 3, franchise: "Fritz", player: "Saquon Barkley(K)", pos: "RB", keeper: true },
    { overall: 4, round: 1, pick: 4, franchise: "Boomer", player: "Jahmyr Gibbs", pos: "RB", keeper: false },
    { overall: 5, round: 1, pick: 5, franchise: "Kam", player: "Ashton Jeanty", pos: "RB", keeper: false },
    { overall: 6, round: 1, pick: 6, franchise: "Devany", player: "Malik Nabers", pos: "WR", keeper: false },
    { overall: 7, round: 1, pick: 7, franchise: "Magoo", player: "CeeDee Lamb", pos: "WR", keeper: false },
    { overall: 8, round: 1, pick: 8, franchise: "DDC", player: "Derrick Henry", pos: "RB", keeper: false },
    { overall: 9, round: 1, pick: 9, franchise: "Trust", player: "Amon-Ra St. Brown", pos: "WR", keeper: false },
    { overall: 10, round: 1, pick: 10, franchise: "Biceps Inc", player: "Bijan Robinson(K)", pos: "RB", keeper: true },
    { overall: 11, round: 1, pick: 11, franchise: "Sherlock", player: "A.J. Brown", pos: "WR", keeper: false },
    { overall: 12, round: 1, pick: 12, franchise: "Vidz", player: "Christian McCaffrey", pos: "RB", keeper: false },
    { overall: 13, round: 2, pick: 1, franchise: "Tino", player: "Jayden Daniels", pos: "QB", keeper: false },
    { overall: 14, round: 2, pick: 2, franchise: "Salsa Dick", player: "Kenneth Walker III", pos: "RB", keeper: false },
    { overall: 15, round: 2, pick: 3, franchise: "Fritz", player: "Kyren Williams", pos: "RB", keeper: false },
    { overall: 16, round: 2, pick: 4, franchise: "Boomer", player: "Chase Brown", pos: "RB", keeper: false },
    { overall: 17, round: 2, pick: 5, franchise: "Kam", player: "Josh Allen", pos: "QB", keeper: false },
    { overall: 18, round: 2, pick: 6, franchise: "Devany", player: "Lamar Jackson", pos: "QB", keeper: false },
    { overall: 19, round: 2, pick: 7, franchise: "Magoo", player: "Josh Jacobs", pos: "RB", keeper: false },
    { overall: 20, round: 2, pick: 8, franchise: "DDC", player: "Bucky Irving", pos: "RB", keeper: false },
    { overall: 21, round: 2, pick: 9, franchise: "Trust", player: "Drake London", pos: "WR", keeper: false },
    { overall: 22, round: 2, pick: 10, franchise: "Biceps Inc", player: "De\'Von Achane", pos: "RB", keeper: false },
    { overall: 23, round: 2, pick: 11, franchise: "Sherlock", player: "Brock Bowers", pos: "TE", keeper: false },
    { overall: 24, round: 2, pick: 12, franchise: "Vidz", player: "Jonathan Taylor", pos: "RB", keeper: false },
    { overall: 25, round: 3, pick: 1, franchise: "Tino", player: "Omarion Hampton", pos: "RB", keeper: false },
    { overall: 26, round: 3, pick: 2, franchise: "Salsa Dick", player: "Garrett Wilson", pos: "WR", keeper: false },
    { overall: 27, round: 3, pick: 3, franchise: "Fritz", player: "Mike Evans", pos: "WR", keeper: false },
    { overall: 28, round: 3, pick: 4, franchise: "Boomer", player: "Tee Higgins", pos: "WR", keeper: false },
    { overall: 29, round: 3, pick: 5, franchise: "Kam", player: "James Cook III", pos: "RB", keeper: false },
    { overall: 30, round: 3, pick: 6, franchise: "Devany", player: "Breece Hall", pos: "RB", keeper: false },
    { overall: 31, round: 3, pick: 7, franchise: "Magoo", player: "Jalen Hurts", pos: "QB", keeper: false },
    { overall: 32, round: 3, pick: 8, franchise: "DDC", player: "Joe Burrow", pos: "QB", keeper: false },
    { overall: 33, round: 3, pick: 9, franchise: "Trust", player: "Tyreek Hill", pos: "WR", keeper: false },
    { overall: 34, round: 3, pick: 10, franchise: "Biceps Inc", player: "Jaxon Smith-Njigba", pos: "WR", keeper: false },
    { overall: 35, round: 3, pick: 11, franchise: "Sherlock", player: "Davante Adams", pos: "WR", keeper: false },
    { overall: 36, round: 3, pick: 12, franchise: "Vidz", player: "Marvin Harrison Jr.", pos: "WR", keeper: false },
    { overall: 37, round: 4, pick: 1, franchise: "Tino", player: "DeVonta Smith", pos: "WR", keeper: false },
    { overall: 38, round: 4, pick: 2, franchise: "Salsa Dick", player: "James Conner", pos: "RB", keeper: false },
    { overall: 39, round: 4, pick: 3, franchise: "Fritz", player: "Patrick Mahomes", pos: "QB", keeper: false },
    { overall: 40, round: 4, pick: 4, franchise: "Boomer", player: "DK Metcalf", pos: "WR", keeper: false },
    { overall: 41, round: 4, pick: 5, franchise: "Kam", player: "Rashee Rice", pos: "WR", keeper: false },
    { overall: 42, round: 4, pick: 6, franchise: "Devany", player: "David Montgomery", pos: "RB", keeper: false },
    { overall: 43, round: 4, pick: 7, franchise: "Magoo", player: "D\'Andre Swift", pos: "RB", keeper: false },
    { overall: 44, round: 4, pick: 8, franchise: "DDC", player: "TreVeyon Henderson", pos: "RB", keeper: false },
    { overall: 45, round: 4, pick: 9, franchise: "Trust", player: "Alvin Kamara", pos: "RB", keeper: false },
    { overall: 46, round: 4, pick: 10, franchise: "Biceps Inc", player: "Courtland Sutton", pos: "WR", keeper: false },
    { overall: 47, round: 4, pick: 11, franchise: "Sherlock", player: "Terry McLaurin", pos: "WR", keeper: false },
    { overall: 48, round: 4, pick: 12, franchise: "Vidz", player: "Jameson Williams", pos: "WR", keeper: false },
    { overall: 49, round: 5, pick: 1, franchise: "Tino", player: "Isiah Pacheco", pos: "RB", keeper: false },
    { overall: 50, round: 5, pick: 2, franchise: "Salsa Dick", player: "RJ Harvey", pos: "RB", keeper: false },
    { overall: 51, round: 5, pick: 3, franchise: "Fritz", player: "George Kittle", pos: "TE", keeper: false },
    { overall: 52, round: 5, pick: 4, franchise: "Boomer", player: "Aaron Jones Sr.", pos: "RB", keeper: false },
    { overall: 53, round: 5, pick: 5, franchise: "Kam", player: "Tony Pollard", pos: "RB", keeper: false },
    { overall: 54, round: 5, pick: 6, franchise: "Devany", player: "Sam LaPorta", pos: "TE", keeper: false },
    { overall: 55, round: 5, pick: 7, franchise: "Magoo", player: "Jaylen Waddle", pos: "WR", keeper: false },
    { overall: 56, round: 5, pick: 8, franchise: "DDC", player: "Calvin Ridley", pos: "WR", keeper: false },
    { overall: 57, round: 5, pick: 9, franchise: "Trust", player: "Jacory Croskey-Merritt", pos: "RB", keeper: false },
    { overall: 58, round: 5, pick: 10, franchise: "Biceps Inc", player: "DJ Moore", pos: "WR", keeper: false },
    { overall: 59, round: 5, pick: 11, franchise: "Sherlock", player: "Jaylen Warren", pos: "RB", keeper: false },
    { overall: 60, round: 5, pick: 12, franchise: "Vidz", player: "George Pickens", pos: "WR", keeper: false },
    { overall: 61, round: 6, pick: 1, franchise: "Tino", player: "Mark Andrews", pos: "TE", keeper: false },
    { overall: 62, round: 6, pick: 2, franchise: "Salsa Dick", player: "Brian Robinson Jr.(K)", pos: "RB", keeper: true },
    { overall: 63, round: 6, pick: 3, franchise: "Fritz", player: "Rome Odunze", pos: "WR", keeper: false },
    { overall: 64, round: 6, pick: 4, franchise: "Boomer", player: "Trey McBride(K)", pos: "TE", keeper: true },
    { overall: 65, round: 6, pick: 5, franchise: "Kam", player: "Travis Kelce", pos: "TE", keeper: false },
    { overall: 66, round: 6, pick: 6, franchise: "Devany", player: "Travis Hunter", pos: "WR", keeper: false },
    { overall: 67, round: 6, pick: 7, franchise: "Magoo", player: "Jakobi Meyers", pos: "WR", keeper: false },
    { overall: 68, round: 6, pick: 8, franchise: "DDC", player: "Tetairoa McMillan", pos: "WR", keeper: false },
    { overall: 69, round: 6, pick: 9, franchise: "Trust", player: "Zay Flowers", pos: "WR", keeper: false },
    { overall: 70, round: 6, pick: 10, franchise: "Biceps Inc", player: "Travis Etienne Jr.", pos: "RB", keeper: false },
    { overall: 71, round: 6, pick: 11, franchise: "Sherlock", player: "Joe Mixon", pos: "RB", keeper: false },
    { overall: 72, round: 6, pick: 12, franchise: "Vidz", player: "Kaleb Johnson", pos: "RB", keeper: false },
    { overall: 73, round: 7, pick: 1, franchise: "Tino", player: "Ricky Pearsall", pos: "WR", keeper: false },
    { overall: 74, round: 7, pick: 2, franchise: "Salsa Dick", player: "Bo Nix", pos: "QB", keeper: false },
    { overall: 75, round: 7, pick: 3, franchise: "Fritz", player: "Jerry Jeudy", pos: "WR", keeper: false },
    { overall: 76, round: 7, pick: 4, franchise: "Boomer", player: "Baker Mayfield", pos: "QB", keeper: false },
    { overall: 77, round: 7, pick: 5, franchise: "Kam", player: "Deebo Samuel", pos: "WR", keeper: false },
    { overall: 78, round: 7, pick: 6, franchise: "Devany", player: "Chris Olave", pos: "WR", keeper: false },
    { overall: 79, round: 7, pick: 7, franchise: "Magoo", player: "Chris Godwin Jr.", pos: "WR", keeper: false },
    { overall: 80, round: 7, pick: 8, franchise: "DDC", player: "T.J. Hockenson", pos: "TE", keeper: false },
    { overall: 81, round: 7, pick: 9, franchise: "Trust", player: "Javonte Williams", pos: "RB", keeper: false },
    { overall: 82, round: 7, pick: 10, franchise: "Biceps Inc", player: "Emeka Egbuka", pos: "WR", keeper: false },
    { overall: 83, round: 7, pick: 11, franchise: "Sherlock", player: "Kyler Murray", pos: "QB", keeper: false },
    { overall: 84, round: 7, pick: 12, franchise: "Vidz", player: "Jayden Reed", pos: "WR", keeper: false },
    { overall: 85, round: 8, pick: 1, franchise: "Tino", player: "Matthew Golden", pos: "WR", keeper: false },
    { overall: 86, round: 8, pick: 2, franchise: "Salsa Dick", player: "Stefon Diggs", pos: "WR", keeper: false },
    { overall: 87, round: 8, pick: 3, franchise: "Fritz", player: "Jordan Mason", pos: "RB", keeper: false },
    { overall: 88, round: 8, pick: 4, franchise: "Boomer", player: "Cooper Kupp", pos: "WR", keeper: false },
    { overall: 89, round: 8, pick: 5, franchise: "Kam", player: "Puka Nacua(K)", pos: "WR", keeper: true },
    { overall: 90, round: 8, pick: 6, franchise: "Devany", player: "Xavier Worthy(K)", pos: "WR", keeper: true },
    { overall: 91, round: 8, pick: 7, franchise: "Magoo", player: "Austin Ekeler", pos: "RB", keeper: false },
    { overall: 92, round: 8, pick: 8, franchise: "DDC", player: "Nico Collins(K)", pos: "WR", keeper: true },
    { overall: 93, round: 8, pick: 9, franchise: "Trust", player: "Quinshon Judkins", pos: "RB", keeper: false },
    { overall: 94, round: 8, pick: 10, franchise: "Biceps Inc", player: "Dak Prescott", pos: "QB", keeper: false },
    { overall: 95, round: 8, pick: 11, franchise: "Sherlock", player: "David Njoku", pos: "TE", keeper: false },
    { overall: 96, round: 8, pick: 12, franchise: "Vidz", player: "Tank Bigsby", pos: "RB", keeper: false },
    { overall: 97, round: 9, pick: 1, franchise: "Tino", player: "Tyjae Spears", pos: "RB", keeper: false },
    { overall: 98, round: 9, pick: 2, franchise: "Salsa Dick", player: "Jordan Addison", pos: "WR", keeper: false },
    { overall: 99, round: 9, pick: 3, franchise: "Fritz", player: "Zach Charbonnet", pos: "RB", keeper: false },
    { overall: 100, round: 9, pick: 4, franchise: "Boomer", player: "Jauan Jennings", pos: "WR", keeper: false },
    { overall: 101, round: 9, pick: 5, franchise: "Kam", player: "Jaydon Blue", pos: "RB", keeper: false },
    { overall: 102, round: 9, pick: 6, franchise: "Devany", player: "Cam Skattebo", pos: "RB", keeper: false },
    { overall: 103, round: 9, pick: 7, franchise: "Magoo", player: "Ladd McConkey(K)", pos: "WR", keeper: true },
    { overall: 104, round: 9, pick: 8, franchise: "DDC", player: "Braelon Allen", pos: "RB", keeper: false },
    { overall: 105, round: 9, pick: 9, franchise: "Trust", player: "Evan Engram", pos: "TE", keeper: false },
    { overall: 106, round: 9, pick: 10, franchise: "Biceps Inc", player: "Tyler Allgeier", pos: "RB", keeper: false },
    { overall: 107, round: 9, pick: 11, franchise: "Sherlock", player: "Keon Coleman", pos: "WR", keeper: false },
    { overall: 108, round: 9, pick: 12, franchise: "Vidz", player: "Drake Maye", pos: "QB", keeper: false },
    { overall: 109, round: 10, pick: 1, franchise: "Tino", player: "Hollywood Brown", pos: "WR", keeper: false },
    { overall: 110, round: 10, pick: 2, franchise: "Salsa Dick", player: "Tyler Warren", pos: "TE", keeper: false },
    { overall: 111, round: 10, pick: 3, franchise: "Fritz", player: "Rhamondre Stevenson", pos: "RB", keeper: false },
    { overall: 112, round: 10, pick: 4, franchise: "Boomer", player: "Keenan Allen", pos: "WR", keeper: false },
    { overall: 113, round: 10, pick: 5, franchise: "Kam", player: "Khalil Shakir", pos: "WR", keeper: false },
    { overall: 114, round: 10, pick: 6, franchise: "Devany", player: "Najee Harris", pos: "RB", keeper: false },
    { overall: 115, round: 10, pick: 7, franchise: "Magoo", player: "J.K. Dobbins", pos: "RB", keeper: false },
    { overall: 116, round: 10, pick: 8, franchise: "DDC", player: "Michael Pittman Jr.", pos: "WR", keeper: false },
    { overall: 117, round: 10, pick: 9, franchise: "Trust", player: "Tyrone Tracy Jr.(K)", pos: "RB", keeper: true },
    { overall: 118, round: 10, pick: 10, franchise: "Biceps Inc", player: "Tucker Kraft", pos: "TE", keeper: false },
    { overall: 119, round: 10, pick: 11, franchise: "Sherlock", player: "Chuba Hubbard(K)", pos: "RB", keeper: true },
    { overall: 120, round: 10, pick: 12, franchise: "Vidz", player: "Brian Thomas Jr.(K)", pos: "WR", keeper: true },
    { overall: 121, round: 11, pick: 1, franchise: "Tino", player: "Kareem Hunt", pos: "RB", keeper: false },
    { overall: 122, round: 11, pick: 2, franchise: "Salsa Dick", player: "Nick Chubb", pos: "RB", keeper: false },
    { overall: 123, round: 11, pick: 3, franchise: "Fritz", player: "Josh Downs", pos: "WR", keeper: false },
    { overall: 124, round: 11, pick: 4, franchise: "Boomer", player: "Rashid Shaheed", pos: "WR", keeper: false },
    { overall: 125, round: 11, pick: 5, franchise: "Kam", player: "Trey Benson", pos: "RB", keeper: false },
    { overall: 126, round: 11, pick: 6, franchise: "Devany", player: "Darnell Mooney", pos: "WR", keeper: false },
    { overall: 127, round: 11, pick: 7, franchise: "Magoo", player: "Marvin Mims Jr.", pos: "WR", keeper: false },
    { overall: 128, round: 11, pick: 8, franchise: "DDC", player: "PHI DEF", pos: "DEF", keeper: false },
    { overall: 129, round: 11, pick: 9, franchise: "Trust", player: "Brock Purdy", pos: "QB", keeper: false },
    { overall: 130, round: 11, pick: 10, franchise: "Biceps Inc", player: "Caleb Williams", pos: "QB", keeper: false },
    { overall: 131, round: 11, pick: 11, franchise: "Sherlock", player: "C.J. Stroud", pos: "QB", keeper: false },
    { overall: 132, round: 11, pick: 12, franchise: "Vidz", player: "Dallas Goedert", pos: "TE", keeper: false },
    { overall: 133, round: 12, pick: 1, franchise: "Tino", player: "Trevor Lawrence", pos: "QB", keeper: false },
    { overall: 134, round: 12, pick: 2, franchise: "Salsa Dick", player: "Jerome Ford", pos: "RB", keeper: false },
    { overall: 135, round: 12, pick: 3, franchise: "Fritz", player: "Rashod Bateman", pos: "WR", keeper: false },
    { overall: 136, round: 12, pick: 4, franchise: "Boomer", player: "Rachaad White", pos: "RB", keeper: false },
    { overall: 137, round: 12, pick: 5, franchise: "Kam", player: "Blake Corum", pos: "RB", keeper: false },
    { overall: 138, round: 12, pick: 6, franchise: "Devany", player: "Justin Fields", pos: "QB", keeper: false },
    { overall: 139, round: 12, pick: 7, franchise: "Magoo", player: "Hunter Henry", pos: "TE", keeper: false },
    { overall: 140, round: 12, pick: 8, franchise: "DDC", player: "Ray Davis", pos: "RB", keeper: false },
    { overall: 141, round: 12, pick: 9, franchise: "Trust", player: "Brandon Aiyuk", pos: "WR", keeper: false },
    { overall: 142, round: 12, pick: 10, franchise: "Biceps Inc", player: "Kyle Monangai", pos: "RB", keeper: false },
    { overall: 143, round: 12, pick: 11, franchise: "Sherlock", player: "Luther Burden III", pos: "WR", keeper: false },
    { overall: 144, round: 12, pick: 12, franchise: "Vidz", player: "Isaac Guerendo", pos: "RB", keeper: false },
    { overall: 145, round: 13, pick: 1, franchise: "Tino", player: "PIT DEF", pos: "DEF", keeper: false },
    { overall: 146, round: 13, pick: 2, franchise: "Salsa Dick", player: "DEN DEF", pos: "DEF", keeper: false },
    { overall: 147, round: 13, pick: 3, franchise: "Fritz", player: "Bhayshul Tuten", pos: "RB", keeper: false },
    { overall: 148, round: 13, pick: 4, franchise: "Boomer", player: "HOU DEF", pos: "DEF", keeper: false },
    { overall: 149, round: 13, pick: 5, franchise: "Kam", player: "Romeo Doubs", pos: "WR", keeper: false },
    { overall: 150, round: 13, pick: 6, franchise: "Devany", player: "BAL DEF", pos: "DEF", keeper: false },
    { overall: 151, round: 13, pick: 7, franchise: "Magoo", player: "Kyle Pitts Sr.", pos: "TE", keeper: false },
    { overall: 152, round: 13, pick: 8, franchise: "DDC", player: "Brandon Aubrey", pos: "PK", keeper: false },
    { overall: 153, round: 13, pick: 9, franchise: "Trust", player: "Jared Goff", pos: "QB", keeper: false },
    { overall: 154, round: 13, pick: 10, franchise: "Biceps Inc", player: "Jake Bates", pos: "PK", keeper: false },
    { overall: 155, round: 13, pick: 11, franchise: "Sherlock", player: "Dalton Kincaid", pos: "TE", keeper: false },
    { overall: 156, round: 13, pick: 12, franchise: "Vidz", player: "MIN DEF", pos: "DEF", keeper: false },
    { overall: 157, round: 14, pick: 1, franchise: "Tino", player: "Dylan Sampson", pos: "RB", keeper: false },
    { overall: 158, round: 14, pick: 2, franchise: "Salsa Dick", player: "Chris Boswell", pos: "PK", keeper: false },
    { overall: 159, round: 14, pick: 3, franchise: "Fritz", player: "Wil Lutz", pos: "PK", keeper: false },
    { overall: 160, round: 14, pick: 4, franchise: "Boomer", player: "Chase McLaughlin", pos: "PK", keeper: false },
    { overall: 161, round: 14, pick: 5, franchise: "Kam", player: "Colston Loveland", pos: "TE", keeper: false },
    { overall: 162, round: 14, pick: 6, franchise: "Devany", player: "Harrison Butker", pos: "PK", keeper: false },
    { overall: 163, round: 14, pick: 7, franchise: "Magoo", player: "KC DEF", pos: "DEF", keeper: false },
    { overall: 164, round: 14, pick: 8, franchise: "DDC", player: "Jaylen Wright", pos: "RB", keeper: false },
    { overall: 165, round: 14, pick: 9, franchise: "Trust", player: "Cameron Dicker", pos: "PK", keeper: false },
    { overall: 166, round: 14, pick: 10, franchise: "Biceps Inc", player: "Isaiah Likely", pos: "TE", keeper: false },
    { overall: 167, round: 14, pick: 11, franchise: "Sherlock", player: "BUF DEF", pos: "DEF", keeper: false },
    { overall: 168, round: 14, pick: 12, franchise: "Vidz", player: "Bryce Young", pos: "QB", keeper: false },
    { overall: 169, round: 15, pick: 1, franchise: "Tino", player: "Jason Sanders", pos: "PK", keeper: false },
    { overall: 170, round: 15, pick: 2, franchise: "Salsa Dick", player: "Jordan Love", pos: "QB", keeper: false },
    { overall: 171, round: 15, pick: 3, franchise: "Fritz", player: "DET DEF", pos: "DEF", keeper: false },
    { overall: 172, round: 15, pick: 4, franchise: "Boomer", player: "Samaje Perine", pos: "RB", keeper: false },
    { overall: 173, round: 15, pick: 5, franchise: "Kam", player: "Ka\'imi Fairbairn", pos: "PK", keeper: false },
    { overall: 174, round: 15, pick: 6, franchise: "Devany", player: "Miles Sanders", pos: "RB", keeper: false },
    { overall: 175, round: 15, pick: 7, franchise: "Magoo", player: "Evan McPherson", pos: "PK", keeper: false },
    { overall: 176, round: 15, pick: 8, franchise: "DDC", player: "Christian Kirk", pos: "WR", keeper: false },
    { overall: 177, round: 15, pick: 9, franchise: "Trust", player: "SF DEF", pos: "DEF", keeper: false },
    { overall: 178, round: 15, pick: 10, franchise: "Biceps Inc", player: "Jack Bech", pos: "WR", keeper: false },
    { overall: 179, round: 15, pick: 11, franchise: "Sherlock", player: "Tyler Bass", pos: "PK", keeper: false },
    { overall: 180, round: 15, pick: 12, franchise: "Vidz", player: "Jake Elliott", pos: "PK", keeper: false },
  ]
});
